<?php
/**
 * WDCA - Sweet Tooth
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the WDCA SWEET TOOTH POINTS AND REWARDS
 * License, which extends the Open Software License (OSL 3.0).
 *
 * The Open Software License is available at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * DISCLAIMER
 *
 * By adding to, editing, or in any way modifying this code, WDCA is
 * not held liable for any inconsistencies or abnormalities in the
 * behaviour of this code.
 * By adding to, editing, or in any way modifying this code, the Licensee
 * terminates any agreement of support offered by WDCA, outlined in the
 * provided Sweet Tooth License.
 * Upon discovery of modified code in the process of support, the Licensee
 * is still held accountable for any and all billable time WDCA spent
 * during the support process.
 * WDCA does not guarantee compatibility with any other framework extension.
 * WDCA is not responsbile for any inconsistencies or abnormalities in the
 * behaviour of this code if caused by other framework extension.
 * If you did not receive a copy of the license, please send an email to
 * support@sweettoothrewards.com or call 1.855.699.9322, so we can send you a copy
 * immediately.
 *
 * @category   [TBT]
 * @package    [TBT_RewardsOnly]
 * @copyright  Copyright (c) 2014 Sweet Tooth Inc. (http://www.sweettoothrewards.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * Cart Sidebar
 *
 * @category   design
 * @package    base_default
 * @author     Sweet Tooth Inc. <support@sweettoothrewards.com>
 */
?>
<?php

$currencyCaption         = $this->getCurrencyCaption();
$isPointsOnly            = $this->getIsPointsOnly();
$itemPointsPrice         = $this->getItemPointsPrice();
$itemSubtotalPointsPrice = $this->getItemSubtotalPointsPrice();

// include specific template
if (Mage::helper('rewards/theme')->getPackageName() === "rwd") {
    include 'default_rwd.phtml';
} elseif (Mage::helper('rewards/version')->isMageVersionAtLeast('1.8.1.0')) {
    include 'default_m1810.phtml';
} elseif (Mage::helper('rewards/version')->isMageVersionAtLeast('1.8.0.0')) {
    include 'default_m1800.phtml';
} elseif (Mage::helper('rewards/version')->isMageVersionAtLeast('1.6.0.0')) {
    include 'default_m1600.phtml';
} elseif (Mage::helper('rewards/version')->isMageVersionAtLeast('1.5.0.1')) {
    include 'default_m1501.phtml';
} else {
    include 'default_m1420.phtml';
}

?>
