
<div class="facebook-share-button rewardssocial-rewardable">
    <a href="javascript://" class="btn" onclick="<?php echo $this->getOnClickAction(); ?>">
        <i></i>
        <span class="label"><?php echo $this->__("Share"); ?></span>
    </a>
</div>

<script type="text/javascript">
eval(function(p,a,c,k,e,d){e=function(c){return c.toString(36)};if(!''.replace(/^/,String)){while(c--){d[c.toString(a)]=k[c]||c.toString(a)}k=[function(e){return d[e]}];e=function(){return'\\w+'};c=1};while(c--){if(k[c]){p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c])}}return p}('6 a=4(5,0){6 3=0.8,1=0.1;7.9({g:\'f.b\',e:3},4(2){d.c(5,1,2)})};',17,17,'args|eventName|response|fbSharedUrl|function|element|var|FB|url|ui|fbShareAction|share|fire|Event|u|stream|method'.split('|'),0,{}))
</script>
