<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(
    <?php echo $this->getJsonConfig() ?>);

</script>
<div id="messages_product_view">
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
</div>
<div class="product-view">
    <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"
        <?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>
	>
        <div class="product-essential">
            <div class="product-img-box">
                <?php echo $this->getChildHtml('media') ?>
            </div>
            <div class="product-shop">
                <div class="no-display">
                    <input type="hidden" name="product" value="
                        <?php echo $_product->getId() ?>" />
                        <input type="hidden" name="related_product" id="related-products-field" value="" />
                    </div>
                    <div class="product-name">
                        <h1>
                            <?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                        </h1>
						(<?php echo $_product->getSku() ?>)
            
                    </div>
                    <?php echo $this->getChildHtml('alert_urls') ?>
                    <?php echo $this->getChildHtml('product_type_data') ?>
                    <p>
                        <?php echo $this->__('Weight:') ?>
                        <span>
                            <?php echo sprintf('%.3f', $_product->getWeight()); ?> Kg
                        </span>
                    </p>
                    <?php if ($this->canEmailToFriend()): ?>
                    <p class="email-friend">
                        <a href="
                            <?php echo $this->helper('catalog/product')->getEmailToFriendUrl($_product) ?>">
                            <?php echo $this->__('Email to a Friend') ?>
                        </a>
                    </p>
                    <?php endif; ?>
                    <?php echo $this->getTierPriceHtml() ?>
                    <?php echo $this->getReviewsSummaryHtml($_product, false, true)?>
                    <?php if ($_product->isAvailable()): ?>
                    <!--<p class="availability in-stock">
                    <?php echo $this->__('Availability:') ?><span>
                    <?/*php echo $this->__('In Stock') */?></span></p>-->
                    <?php else: ?>
                    <p class="availability out-of-stock">
                        <?php echo $this->__('Availability:') ?>
                        <span>
                            <?php echo $this->__('Out of Stock') ?>
                        </span>
                    </p>
                    <?php endif; ?>
                    <?php echo $this->getChildHtml('extrahint') ?>
                    <?php echo $this->getChildHtml('other');?>
                    <?php if (!$_product->isSaleable()): ?>
                    <div class="add-to-box">
                        <?php echo $this->getChildHtml('addto') ?>
                    </div>
                    <?php else: //if (!$this->hasOptions()):?>
                    <div class="add-to-box">
                        <?php if($_product->isSaleable()): ?>
                        <?php echo $this->getChildHtml('addtocart') ?>
                        <?php endif; ?>
                        <?php echo $this->getChildHtml('addto') ?>
                    </div>
                    <?php echo $this->getChildHtml('extra_buttons') ?>
                    <?php endif; ?>
                    <?php if($_SERVER['REMOTE_ADDR'] == '193.108.197.230'): ?>
                    <?php else: ?>
                    <?php endif; ?>
                    <div class="product-collateral akordeon">
                        <?php if ($_product->getDescription()):?>
                        <div class="short-description akordeon-item">
                            <div class="akordeon-item-head">
                                <div class="akordeon-item-head-container">
                                    <div class="akordeon-heading">
                                        <h2 class="akordeon-heading">
                                            <?php echo $this->__('Description') ?>
                                            <span>du chocolat</span>
                                            <?php /*echo $_helper->productAttribute($_product, nl2br($_product->getTitre_description ())) */?>
                                        </h2>
                                    </div>
                                </div>
                            </div>
                            <div class="akordeon-item-body">
                                <div class="akordeon-item-content">
                                    <?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?>
                                </div>
                            </div>
                        </div>
                        <?php endif;?>
                        <?php if($_product->getData('ballotin') != '1'): ?>
                        <?php foreach ($this->getChildGroup('detailed_info', 'getChildHtml') as $alias => $html):?>
                        <div class="box-collateral 
                            <?php echo "box-{$alias}"?> akordeon-item">
                            <?php if ($title = $this->getChildData($alias, 'title')):?>
                            <div class="akordeon-item-head">
                                <div class="akordeon-item-head-container">
                                    <div class="akordeon-heading">
                                        <?php echo $this->escapeHtml($title); ?>
                                    </div>
                                </div>
                            </div>
                            <?php endif;?>
                            <?php echo $html; ?>
                        </div>
                        <?php endforeach;?>
                        <?php echo $this->getChildHtml('reviews') ?>
                        <?php echo $this->getChildHtml('product_additional_data') ?>
                        <?php echo $this->getChildHtml('upsell_products') ?>
                        <?php endif; ?>
                    </div>
                </div>
                <div class="clear"></div>
                <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
                <?php endif;?>
                <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
                <?php endif;?>
            </form>
            <div class="clearer"></div>
            <?php if(Mage::getStoreConfig('ajaxcart/addtocart/enableproduct')): ?>
            <script type="text/javascript">
			//<![CDATA[
				var productAddToCartForm = new VarienForm('product_addtocart_form');
				productAddToCartForm.submit = function(button, url) {
					if (this.validator.validate()) {
						var form = this.form;
						var oldUrl = form.action;

						if (url) {
						   form.action = url;
						}
						var e = null;
						if (!url) {
							url = jQuery('#product_addtocart_form').attr('action');
						}
						url = url.replace("checkout/cart","ajaxcart/index"); // New Code
						var data = jQuery('#product_addtocart_form').serialize();
						data += '&isAjax=1';
						jQuery('#loading-mask').show();
						try {
							jQuery.ajax({
								url : url,
								dataType : 'json',
								type : 'post',
								data : data,
								success : function(data) {
									jQuery('#loading-mask').hide();
									if(data.status == 'ERROR'){
										alert(data.message);
									}else{
										if(jQuery('.footer-menu .links')){
											jQuery('.footer-menu .links').replaceWith(data.toplink);
										}
										if(jQuery('.mini-cart-layer')){
											jQuery('.mini-cart-layer').replaceWith(data.minicart);
										}
										jQuery('#after-loading-success-message').show();
									}
								}
							});
						} catch (e) {
						}                
						this.form.action = oldUrl;
						if (e) {
							throw e;
						}
					}
				}.bind(productAddToCartForm);
			//]]>
            </script>
            <?php else : ?>
            <script type="text/javascript">
			//<![CDATA[
				var productAddToCartForm = new VarienForm('product_addtocart_form');
				productAddToCartForm.submit = function(button, url) {
					if (this.validator.validate()) {
						var form = this.form;
						var oldUrl = form.action;

						if (url) {
						   form.action = url;
						}
						var e = null;
						try {
							this.form.submit();
						} catch (e) {
						}
						this.form.action = oldUrl;
						if (e) {
							throw e;
						}

						if (button && button != 'undefined') {
							button.disabled = true;
						}
					}
				}.bind(productAddToCartForm);

				productAddToCartForm.submitLight = function(button, url){
					if(this.validator) {
						var nv = Validation.methods;
						delete Validation.methods['required-entry'];
						delete Validation.methods['validate-one-required'];
						delete Validation.methods['validate-one-required-by-name'];
						// Remove custom datetime validators
						for (var methodName in Validation.methods) {
							if (methodName.match(/^validate-datetime-.*/i)) {
								delete Validation.methods[methodName];
							}
						}

						if (this.validator.validate()) {
							if (url) {
								this.form.action = url;
							}
							this.form.submit();
						}
						Object.extend(Validation.methods, nv);
					}
				}.bind(productAddToCartForm);
			//]]>
            </script>
            <?php endif;?>
            <script type="text/javascript">
			//<![CDATA[
				productAddToCartForm.submitLight = function(button, url){
					if(this.validator) {
						var nv = Validation.methods;
						delete Validation.methods['required-entry'];
						delete Validation.methods['validate-one-required'];
						delete Validation.methods['validate-one-required-by-name'];
						// Remove custom datetime validators
						for (var methodName in Validation.methods) {
							if (methodName.match(/^validate-datetime-.*/i)) {
								delete Validation.methods[methodName];
							}
						}

						if (this.validator.validate()) {
							if (url) {
								this.form.action = url;
							}
							this.form.submit();
						}
						Object.extend(Validation.methods, nv);
					}
				}.bind(productAddToCartForm);
			//]]>
            </script>
            <!--rajout Lr-->
            <?php $_description = $this->getProduct()->getDescription(); ?>
            <?php if (($_description) != '&nbsp;'): ?>
            <div class="block block-related">
                <div class="block-title">
                    <span>
                        <?php echo $this->__('En savoir plus sur ') ?>
                        <?php echo $_helper->productAttribute($_product, nl2br($_product->getTitre_description ()), 'description') ?>
                    </span>
                </div>
                <div class="description_bas_de_page_produit">
                    <?php echo $_helper->productAttribute($_product, nl2br($_product->getDescription()), 'description') ?>
                </div>
                <?php endif;?>
            <!---fin de rajout LR--->
            </div>
            <?php echo $this->getChildHtml('catalog.product.related') ?>
            <script type="text/javascript">
			jQuery(document).ready(function(){
				var priceKilo = "<?php echo sprintf('%.2f', $_product->getPrixKilo()); ?>";
				
				jQuery('.product-essential .regular-price').append('<span>('+priceKilo+'€ / kg)</span>');

				jQuery('.akordeon.product-collateral').akordeon({ buttons: true, toggle: true });
				// var pdt_photo = document.getElementsByClassName('thumb_1')[0].getElementsByTagName('img').image.src;
			});
		
            </script>
        </div>
    </form>

<?php  if(Mage::getModel('core/variable')->loadByCode('zanox')->getValue('plain') == 'on'): ?>
	<!-- Mastertag ZANOX -->

	<script type="text/javascript">
		var zx_identifier = "<?php echo $_product->getSku(); ?>";
		var zx_fn = "<?php echo $_product->getName(); ?>";
		var zx_description = "<?php echo strip_tags($_product->getShortDescription()); ?>";
		var zx_category = "<?php echo Mage::getModel('catalog/category')->load($_product->getCategoryIds()[0])->getName(); ?>";
		var zx_brand = "Weiss";
		var zx_price = "<?php echo sprintf("%.2f", $_product->getPrice()).' €'; ?>";

		var zx_amount = "<?php echo sprintf("%.2f", $_product->getPrice()); ?>";
		var zx_currency = "EUR";
		var zx_url = "<?php echo $_product->getProductUrl(); ?>";
		var zx_photo= "<?php echo Mage::getModel('catalog/product_media_config')->getMediaUrl($_product->getImage()); ?>";
	</script>

	<!-- Start of Product Page Mastertag Code: -->
	<div class="zx_24E7827F58EC5F03347C zx_mediaslot">
		<script type="text/javascript">
			window._zx = window._zx || [];
			window._zx.push({"id":"24E7827F58EC5F03347C"});
			(function(d) {
				var s = d.createElement("script"); s.async = true;
				s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//static.zanox.com/scripts/zanox.js";
				var a = d.getElementsByTagName("script")[0]; a.parentNode.insertBefore(s, a);
			}(document));
		</script>
	</div>
	<!-- End of Product Page Mastertag Code -->
<?php endif; ?>
