<div class="page-title">
    <h1><?php echo $this->__('Checkout') ?></h1>
</div>
<script type="text/javascript" src="<?php echo $this->getJsUrl('varien/accordion.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/opcheckout.js') ?>"></script>
<ol class="opc" id="checkoutSteps">
<?php $i=0; foreach($this->getSteps() as $_stepId => $_stepInfo): ?>
<?php if (!$this->getChild($_stepId) || !$this->getChild($_stepId)->isShow()): continue; endif; $i++ ?>
    <li id="opc-<?php echo $_stepId ?>" class="section<?php echo !empty($_stepInfo['allow'])?' allow':'' ?><?php echo !empty($_stepInfo['complete'])?' saved':'' ?>">
        <div class="step-title">
            <!-- <span class="number"><?php echo $this->__('step ').$i ?></span> -->
            <span class="number" style="display:none"><?php echo $this->__('Edit'); ?></span>
            <span class="step-number"><?php echo $i ?></span>
            <h2><?php echo $_stepInfo['label'].' '.($_stepId == 'billing' ? '<span>(facultative)</span>' : '') ?></h2>
            <a href="#"><?php echo $this->__('Edit') ?></a>
        </div>
        <div id="checkout-step-<?php echo $_stepId ?>" class="step a-item" style="display:none;">
            <?php echo $this->getChildHtml($_stepId) ?>
        </div>
    </li>
<?php endforeach ?>
</ol>
<script type="text/javascript">
//<![CDATA[
    var accordion = new Accordion('checkoutSteps', '.step-title', true);
    <?php if($this->getActiveStep()): ?>
    accordion.openSection('opc-<?php echo $this->getActiveStep() ?>');
    <?php endif ?>
    var checkout = new Checkout(accordion,{
        progress: '<?php echo $this->getUrl('checkout/onepage/progress') ?>',
        review: '<?php echo $this->getUrl('checkout/onepage/review') ?>',
        saveMethod: '<?php echo $this->getUrl('checkout/onepage/saveMethod') ?>',
        failure: '<?php echo $this->getUrl('checkout/cart') ?>'}
    );
    setTimeout(function () {
        checkout.watch('currentStep',function (prop, oldval, val) {
            
            switch(val) {
                case 'shipping' :
                    tagmanager_event('changeCheckoutStep',{'step':'Adresse de livraison'});
                    break;
                case 'billing' :
                    tagmanager_event('changeCheckoutStep',{'step':'Adresse de facturation'});
                    break;
                case 'shipping_method' :
                    tagmanager_event('changeCheckoutStep',{'step':'Mode de livraison'});
                    break;
                case 'payment' :
                    tagmanager_event('changeCheckoutStep',{'step':'Mode de paiement'});
                    break;
                case 'review' :
                    tagmanager_event('changeCheckoutStep',{'step':'Récapitulatif'});
                    break;
                default:
                    tagmanager_event('changeCheckoutStep',{'step':'Adresse de livraison'});
                    break;
            }
        });
        tagmanager_event('changeCheckoutStep',{'step':'Adresse de livraison'});
    },200);


//]]>
</script>
