<div class="page-title">
    <h1><?php echo $this->__('Reset a Password'); ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml(); ?>
<form action="<?php echo $this->getUrl('*/*/resetpasswordpost', array('_query' => array('id' => $this->getCustomerId(), 'token' => $this->getResetPasswordLinkToken()))); ?>" method="post" id="form-validate">
    <div class="block block-personal-info">
        <div class="block-title">
            <strong><span><?php echo $this->__('Reset a Password') ?></span></strong>
        </div>
        <div class="block-content">
            <ul class="form-list">
                <li class="fields">
                    <div class="field">
                        <div class="input-box">
                            <input type="password" class="input-text required-entry validate-password" name="password" id="password" placeholder="<?php echo $this->__('New Password'); ?> *" />
                        </div>
                    </div>
                    <div class="field">
                        <div class="input-box">
                            <input type="password" class="input-text required-entry validate-cpassword" name="confirmation" id="confirmation" placeholder="<?php echo $this->__('Confirm New Password'); ?> *" />
                        </div>
                    </div>
                </li>
            </ul>
        </div>
    </div>
    <div class="buttons-set">
        <button type="submit" title="<?php echo $this->__('Reset a Password'); ?>" class="button"><span><span><?php echo $this->__('Reset a Password'); ?></span></span></button>
    </div>
</form>
<script type="text/javascript">
/*<![CDATA[*/
    var dataForm = new VarienForm('form-validate', true);
/*]]>*/
</script>
