<?php if ($this->getCategories()->count() && Mage::getStoreConfig('blog/menu/category')): ?>  
<div class="block block-blog-categories">
    <div class="block-title">
        <strong><span><?php echo Mage::helper('blog')->__('Categories'); ?></span></strong>
    </div>
    <div class="block-content">
        <div class="akordeon category-list">
            <?php $cats = $this->getCategories(); ?>
            <?php foreach ($cats as $cat): ?>
            <div class="akordeon-item has-no-children">
                <div class="akordeon-item-head">
                    <div class="akordeon-item-head-container">
                        <div class="akordeon-heading">
                            <a href="<?php echo $cat->getAddress(); ?>"><?php echo $cat->getTitle(); ?></a>
                        </div>
                    </div>
                </div>
            </div>
            <?php endforeach; ?>
        </div>
        <script type="text/javascript">
            jQuery(document).ready(function(){
                jQuery('.akordeon.category-list').akordeon({ buttons: false, toggle: true });
            });
        </script>
    </div>    
</div>
<?php endif; ?>
<?php if ($posts = $this->getRecent()): ?>
<div class="block block-blog-recent">
    <div class="block-title">
        <strong><span><?php echo Mage::helper('blog')->__('Recent Posts'); ?></span></strong>
    </div>
    <div class="block-content">
        <ul>
        <?php foreach ($posts as $post): ?>
            <li>
                <div class="post-image">
                <?php
                    if($post_image = $post->getImage()){
                ?>
                    <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$post_image; ?>" alt=""/>
                <?php
                    }
                ?>
                </div>
                <a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a>
                <div class="post-time"><?php echo Mage::helper('core')->formatDate($post->getCreatedTime(), 'long', false); ?></div>
                <div class="comments-count"><?php echo $post->getCommentCount(); ?>&nbsp;<?php echo $this->__('Comment(s)'); ?></div>
                <div class="clear"></div>
            </li>
        <?php endforeach; ?>
        </ul>
    </div>    
</div>
<?php endif; ?>

<?php echo $this->getChildHtml('blog_tags'); ?>
