<?php $_description = $this->getProduct()->getDescription(); ?>
<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>



<?php if ($_description): ?>
<!--<div class="akordeon-item-head">
    <div class="akordeon-item-head-container">
        <div class="akordeon-heading">
            <? /*php echo $this->__('Details') */?>
        </div>
    </div>
</div>-->
<div class="akordeon-item-body">
    <div class="akordeon-item-content" style="margin-bottom:10px;">
        <?php echo $this->helper('catalog/output')->productAttribute($this->getProduct(), $_description, 'description') ?>
		 <?php echo $_helper->productAttribute($_product, nl2br($_product->getName()), 'name') ?>
    </div>
</div>
<?php endif; ?>
