<div class="discount">
    <h2><?php echo $this->__('Discount Codes') ?></h2>
    
    <form id="discount-coupon-form" action="<?php echo $this->getUrl('checkout/cart/couponPost') ?>" method="post">
    <div class="discount-form">
        <label for="coupon_code"><?php echo $this->__('Enter your coupon code if you have any.') ?></label>
        <input type="hidden" name="remove" id="remove-coupone" value="0" />
        <div class="input-box">
            <input class="input-text" id="coupon_code" name="coupon_code" value="" />
        </div>
        <div class="buttons-set">
            <button type="button" title="<?php echo $this->__('Apply Coupon') ?>" class="button" onclick="discountForm.submit(false)" value="<?php echo $this->__('Apply Coupon') ?>"><span><span><?php echo $this->__('Apply Coupon') ?></span></span></button>
        </div>
    </div>
    </form>
    
    
    <?php if ($this->getUtilizedCoupons()): ?>
  
       <div class="multiple_coupon_container" >
        <h2><?php echo $this->__('Your Applied Coupons'); ?></h2>
        <ul class="multiple_coupon">
        <?php $ccnt = 0; ?>
        <?php foreach ($this->getUtilizedCoupons() as $coupon): ?>
            <li class="item">
                <div class="coupon-title"><?php echo $coupon; ?></div>
                <div class="coupon-cancle">
                    <form id="utilized-coupon-cancle-frm-<?php echo $ccnt; ?>" action="<?php echo $this->getUrl('multicoupon/index/removeCouponCode') ?>" method="post">
                        <input type="hidden" name="utilized_coupon_cancel" value="<?php echo $coupon; ?>" />
                        <button value="Apply Coupon" onclick="javascript: $('utilized-coupon-cancle-frm-<?php echo $ccnt; ?>').submit(); return false;" class="button" title="Cancle" type="button"><span><span><?php echo $this->__('Cancel'); ?></span></span></button>
                    </form>
                </div>
            </li>
            <?php $ccnt++; ?>
        <?php endforeach; ?>
        </ul>
        </div>
    <?php endif; ?>
    
    
</div>

<script type="text/javascript">
//<![CDATA[
var discountForm = new VarienForm('discount-coupon-form');
discountForm.submit = function (isRemove) {
    if (isRemove) {
        $('coupon_code').removeClassName('required-entry');
        $('remove-coupone').value = "1";
    } else {
        $('coupon_code').addClassName('required-entry');
        $('remove-coupone').value = "0";
    }
    return VarienForm.prototype.submit.bind(discountForm)();
}
//]]>
</script>