<script type="text/javascript">

//Initialize first demo:
ddaccordion.init({
	headerclass: "accordion_titre", //Shared CSS class name of headers group
	contentclass: "accordion_content", //Shared CSS class name of contents group
	revealtype: "click", //Reveal content when user clicks or onmouseover the header? Valid value: "click", "clickgo", or "mouseover"
	mouseoverdelay: 200, //if revealtype="mouseover", set delay in milliseconds before header expands onMouseover
	collapseprev: true, //Collapse previous content (so only one open at any time)? true/false 
	defaultexpanded: [0], //index of content(s) open by default [index1, index2, etc]. [] denotes no content.
	onemustopen: false, //Specify whether at least one header should be open always (so never all headers closed)
	animatedefault: false, //Should contents open by default be animated into view?
	persiststate: true, //persist state of opened contents within browser session?
	toggleclass: ["", "accordion_open"], //Two CSS classes to be applied to the header when it's collapsed and expanded, respectively ["class1", "class2"]
	togglehtml: ["none", "", ""], //Additional HTML added to the header when it's collapsed and expanded, respectively  ["position", "html1", "html2"] (see docs)
	animatespeed: "fast", //speed of animation: integer in milliseconds (ie: 200), or keywords "fast", "normal", or "slow"
	oninit:function(expandedindices){ //custom code to run when headers have initalized
		//do nothing
	},
	onopenclose:function(header, index, state, isuseractivated){ //custom code to run whenever a header is opened or closed
		//do nothing
	}
})


</script>


<div class="contenu_page_static" style="padding-bottom:15px;">

<p>Les présentes Conditions Générales de Vente (ci-après « C.G.V ») de la S.A.S Weiss, définissent les termes et conditions de toutes transactions effectuées dans le cadre d'un système de vente à distance sur Internet.</p>

            <div class="scroll-pane" id="texte_scrollable">
            
			<br>
			<div class="accordion_titre accordion_open" headerindex="0h">Champ d’application des conditions générales de vente</div>
            <div class="accordion_content" contentindex="0c" style="display: block;">
               
                <ul>
      <li><u>La société</u></li>     
				</ul>
<p>Le site internet www.chocolat-weiss.fr est la propriété le S.A.S Weiss, Société par Actions Simplifiées au capital de 9 900 000 euros immatriculée au Registre du Commerce et des Sociétés de Saint-Etienne sous le numéro 353 395 346 00060 RCS Saint Etienne, dont le siège social est situé 1, rue Eugène Weiss, 42006 Saint Etienne Cedex 1.</p>
         
				<ul>
					  <li>
				     <u>Le client </u></li>
				</ul>
                
                <p>Toute personne physique majeure achetant à des fins qui n'entrent pas dans le cadre de son activité commerciale, industrielle artisanale ou libérale (ci-après « le Client ») reconnait avoir la pleine capacité à s'engager au titre des présentes CGV lorsqu'elle commande et achète des produits de la société.</p>
				<ul>
 					 <li>
			         <u>L'application des CGV </u></li>
				</ul>
                <p>Les présentes conditions générales de vente annulent et remplacent toutes conditions ou documents antérieurs et s'appliquent à toutes les consultations et à toutes les commandes réalisées sur le site internet www.chocolat-weiss.fr. (ci-après le site).</p>
<p>Les conditions générales de vente applicables sont celles en vigueur au jour de la passation de votre commande.</p>
<p>Aucune condition particulière, ni autre condition générale émanant du client ne peuvent, sans accord express de la S.A.S. Weiss, prévaloir sur les présentes conditions.</p>
           </div>
            
            
            
            <div class="accordion_titre" headerindex="1h">L'offre de produit</div>
            <div class="accordion_content" contentindex="1c" style="display: none;">
                <div>
					<p>Les produits sont des marchandises définies au catalogue de vente du site internet <a href="http://www.chocolat-weiss.fr/" _mce_href="http://www.chocolat-weiss.fr/">www.chocolat-weiss.fr</a>. La S.A.S Weiss se réserve le droit de modifier ses offres à tout moment. Elles ne sont valables que pour une réponse immédiate et dans la limite des stocks disponibles. Les articles sont des produits alimentaires à consommer de préférence avant une date optimale (D.L.U.O.).</p>
                </div>
            </div>


			<div class="accordion_titre" headerindex="2h">Les prix</div>
            <div class="accordion_content" contentindex="2c" style="display: none;">
                <div>
                <p>Les prix sont formulés en euros toutes taxes comprises. Les tarifs sont modifiables sans préavis.<br />
  <strong>Les taux de TVA s'appliquent en fonction des 10 catégories définies dans le décret n°76-692 du 13 juillet 1976 modifié par le décret n° 2003-702 du 29 juillet 2003. </strong><br />
  <strong><br />
    Rappel des grands points à retenir :</strong><strong><br />
      </strong>
      <ul>
      <li>le chocolat noir est à 5,5 %, sauf les tablettes fourrées et autres grandes bouchées fourrées</li>

<li>le chocolat au lait est à 20.00 % </li>
 <li>les bonbons de chocolat (noir, lait, blanc) sont à 5,5 %</li>
<li>les pâtes à tartiner sont à 5,5 %</li>
<li>les sujets faits avec des chocolats différents (noir + lait) sont à 20.00 %</li>
<li>les produits de confiserie sont à 20.00 %</li></ul></p>
              </div>
            </div>
            
            <div class="accordion_titre" headerindex="3h">Commande</div>
            <div class="accordion_content" contentindex="3c" style="display: none;">
                <div>
					<p>La passation d'une commande entraîne l'acceptation des Conditions Générales de Vente («&nbsp;CGV&nbsp;») par le client nonobstant toutes réserves ou exigences qui pourraient l'accompagner. Cette acceptation est confirmée par le fait que le client doit valider son acceptation avant de finaliser sa commande.</p>
<p>La société&nbsp;ne considère comme commandes que celles qu'elle a acceptées et confirmées. Aucune commande ne pourra être annulée dès lors qu'elle aura quitté notre centre d'expédition.<br />
  En cas d'indisponibilité d'un produit sur une commande, la société contactera le client pour lui proposer&nbsp;:</p>
<p>- le remplacement de son produit par un produit de valeur et de qualité équivalente,</p>
<p>- une livraison ultérieure lorsque le stock le permettra,</p>
<p>- l'annulation de sa commande et son remboursement dans un délai de 14 jours après la notification.</p>
<p>Le client se doit de renseigner des champs personnels pour la création de son compte, la facturation et la livraison. Toutes les informations fournies doivent être vérifiées par le client. La SAS Weiss dégage toute responsabilité sur l'inexactitude des données communiquées. Elle ne sera pas responsable d'erreur de livraison dans la mesure où les informations fournies lors de la passation de commande sont inexactes.</p>
               
<p>Modalités de rétractation</p>

<p>Conformément à la réglementation en vigueur, le droit de rétractation ne peut pas être exercé pour les contrats de produits alimentaires qui, par leur nature, ne peuvent être réexpédiés ou peuvent se détériorer ou se périmer rapidement.(<a href="http://vosdroits.service-public.fr/particuliers/F10485.xhtml#N100D5">vosdroits.service-public.fr</a>)</p>
                </div>
            </div>
                        
            <div class="accordion_titre" headerindex="4h">La livraison</div>
            <div class="accordion_content" contentindex="4c" style="display: none;">
                <div>
                <ul>
  <li>
   <u> Les délais</u></li>
    </ul>
 
<p>Les délais de livraison varient en fonction du prestataire choisi. (Voir le détail sur <a title="Livraison chocolat weiss" href="qualite-de-livraison.html" _mce_href="
/qualite-de-livraison">Livraison)</a><br />
Ils ne sont donnés qu’à titre indicatif. Weiss s'engage à tout mettre en oeuvre pour respecter ces délais et à proposer une alternative en cas de retard ou de non livraison. </p>
                	
                    <ul>
                    <li>
                   <u> Cas de force majeure</u>
                    </li>
                    </ul>
                    <p>Le chocolat Weiss est exonéré de sa responsabilité dans tous les cas de force majeure liés à des circonstances imprévisibles et extérieures, notamment en cas de sinistres ou d'intempéries reconnus, de grèves des prestataires logistiques, ou de tout autre événement susceptible de perturber la bonne circulation des marchandises et/ou le fonctionnement des réseaux informatiques et de l'internet. <br />
  En cas de litige, nous recherchons avec nos clients les meilleures solutions commerciales.</p>
					
                    <ul>
 					 <li>
                    <u> La réception</u>
                     </li>
                     </ul>
                     <p>Le réceptionnaire doit vérifier la qualité, la quantité, le poids, et le bon état des marchandises livrées.</p>
<p>En cas de livraison par un tiers (société de transport, poste…) présentant des signes manifestes de détérioration ou de non-conformité, le réceptionnaire devra <strong>immédiatement</strong> apporter des réserves auprès du prestataire, par une mention explicite sur le bon de livraison et confirmer cette réserve à notre service client dans les 48 heures<br />
  - en téléphonant au 00 33 4 77 49 38 99<br />
  - par email à <a href="mailto:serviceclients@weiss.fr" _mce_href="mailto:serviceclients@weiss.fr">service.clients@weiss.fr</a><br />
  - ou par courrier à Chocolat Weiss, Service clients Internet, 1 rue Eugène Weiss, BP 242 42006 Saint Etienne cedex 1.<br />
  Toute réclamation dans nos ordres, faite 48 heures après la livraison, ne pourra être retenue.</p>
  </div>
  </div>
  
    <div class="accordion_titre" headerindex="5h">Commande non conforme</div>
            <div class="accordion_content" contentindex="5c" style="display: none;">
                   
                   <div><p>« Les produits sont garantis contre les défauts susvisés pendant une durée de six mois pour les bonbons de confiserie, et pendant une durée de deux ans pour les tablettes, le tout à compter de la date de livraison et sur le territoire.
Toutefois, le Client sera seul responsable des fautes qu'il pourrait commettre à compter de la date de livraison, notamment de toute mauvaise condition de conservation et/ou de transport des produits ou du non respect de la date limite de consommation ou d’utilisation optimale indiquée sur l'emballage.
</p>
<p>Les réclamations doivent être transmises à : WEISS SAS, 1 rue Eugène Weiss 42006 Saint Etienne Cedex 2 ou par email en utilisant le <a href="http://www.chocolat-weiss.fr/contacts">formulaire de contact</a>.</p>
<p>Indépendamment de la garantie commerciale, le vendeur reste tenu de la garantie légale de conformité mentionnée aux articles L. 211-4 à L. 211-13 du Code de la Consommation et de celle relative aux défauts de la chose vendue, dans les conditions prévues aux articles 1641 à 1648 et 2232 du Code Civil. 
<vr />Article L 211-4 du Code de la Consommation : « Le vendeur est tenu de livrer un bien conforme au contrat et répond des défauts de conformité existant lors de la délivrance. 
Il répond également des défauts de conformité résultant de l'emballage, des instructions de montage ou de l'installation lorsque celle-ci a été mise à sa charge par le contrat ou a été réalisée sous sa responsabilité »
<br />Article L 211-5 du Code de la Consommation : « Pour être conforme au contrat, le bien doit : 
<br />1° Etre propre à l'usage habituellement attendu d'un bien semblable et, le cas échéant : 
- correspondre à la description donnée par le vendeur et posséder les qualités que celui-ci a présentées à l'acheteur sous forme d'échantillon ou de modèle ; 
- présenter les qualités qu'un acheteur peut légitimement attendre eu égard aux déclarations publiques faites par le vendeur, par le producteur ou par son représentant, notamment dans la publicité ou l'étiquetage ; 
<br />2° Ou présenter les caractéristiques définies d'un commun accord par les parties ou être propre à tout usage spécial recherché par l'acheteur, porté à la connaissance du vendeur et que ce dernier a accepté. »
<br />Article L 211-12 du Code de la Consommation : « L'action résultant du défaut de conformité se prescrit par deux ans à compter de la délivrance du bien. » 
<br />Article 1641 du Code Civil : « Le vendeur est tenu de la garantie à raison des défauts cachés de la chose vendue qui la rendent impropre à l'usage auquel on la destine, ou qui diminuent tellement cet usage que l'acheteur ne l'aurait pas acquise, ou n'en aurait donné qu'un moindre prix, s'il les avait connus. »
Premier alinéa de l’article 1648 du Code Civil : « L'action résultant des vices rédhibitoires doit être intentée par l'acquéreur dans un délai de deux ans à compter de la découverte du vice. » 
</p><p>En cas de non-conformité avec la commande, le client doit en avertir la société dans un délai de cinq jours, si le vice est apparent, et dans le même délai à partir du moment où il en aura eu connaissance, si le vice est caché.</p>
<p>Les défauts de matières, mêmes cachés, ainsi que les erreurs de dimensions, de qualité, de quantités, de poids n'obligent la société qu'au remplacement pur et simple des produits incriminés sans aucune indemnité. Les produits ainsi remplacés restant sa propriété. La société n'accepte aucun retour de marchandise sans l'avoir préalablement autorisé.</p>
</div>
            </div>
      <div class="accordion_titre" headerindex="6h">Conditions de paiement</div>
            <div class="accordion_content" contentindex="6c" style="display: none;">
                <div>
                <p>Les marchandises sont payables au comptant à la prise de commande selon les moyens de paiement mis à disposition.</p>
<ul>
  <li><strong>Paiement sécurisé par carte bancaire</strong> sur le terminal de paiement de La BNP. </li>
  <li><strong>Virement bancaire</strong> sur notre compte bancaire dont les coordonnées figurent ci-dessous&nbsp;:</li>
</ul>
<p><span _mce_style="text-decoration: underline;">Titulaire du compte</span>&nbsp;: Chocolat Weiss, 1 rue Eugène Weiss, BP242, 42006 Saint Etienne, Cedex 1, France<br />
  <span _mce_style="text-decoration: underline;">Code Banque</span>&nbsp;: 30004<br />
  <span _mce_style="text-decoration: underline;">Code Agence </span>02683<br />
  <span _mce_style="text-decoration: underline;">Numéro de compte</span>&nbsp;: 000&nbsp;101&nbsp;062 90<br />
  <span _mce_style="text-decoration: underline;">Clé RIB</span>&nbsp;: 96<br />
<span _mce_style="text-decoration: underline;">Agence de domiciliation</span> BNP Paribas Loire Entreprise</p>
<p><span _mce_style="text-decoration: underline;">IBAN</span> FR 76 3000 4026 8300 0101 0629 096<br />
  <span _mce_style="text-decoration: underline;">BIC</span> BNPAFRPPLAE</p>
  
  <p>Toutes les commandes sont traitées et, uniquement expédiées, à réception du paiement.</p>
  </div>    
  </div>    
            
           
       <div class="accordion_titre" headerindex="7h">Sécurité et cryptage</div>
            <div class="accordion_content" contentindex="7c" style="display: none;">
                <div>
<p>Nous utilisons le terminal de paiement Merc@net de BNP Paribas. Ce terminal vous assure la confidentialité des données avec le cryptage SSL. Il respecte les standards de sécurité PCI DSS concernant le stockage et la circulation des données sensibles.</p>
  </div>    
  </div>   
  
      <div class="accordion_titre" headerindex="8h">Réserve de propriété</div>
            <div class="accordion_content" contentindex="8c" style="display: none;">
                <div>
                <p>Le transfert de propriété des produits au profit de l'acquéreur, ne sera réalisé qu'après complet paiement du prix par ce dernier, et ce quel que soit la date de livraison desdits produits. <br />
  En revanche, le transfert des risques de perte et de détérioration des produits sera réalisé dès la livraison et réception desdits produits par l'acquéreur.</p>

  </div>    
  </div>   
  
       <div class="accordion_titre" headerindex="9h">Mentions légales et clauses juridiques</div>
      <div class="accordion_content" contentindex="9c" style="display: none;">
                <div>
                <ul>
      <li><u>Loi informatique et libertés</u></li>
    </ul>
  </li>

<p>Conformément aux dispositions de la loi Informatique et libertés modifiée, le site internet www.chocolat-weiss.fr a été déclaré et enregistré auprès de la CNIL sous le numéro 1438638. Vous disposez d'un droit d'accès, de modification, de rectification et de suppression des données nominatives vous concernant.</p>
<p>Si vous souhaitez exercer votre droit mentionné ci-dessus ou ne plus recevoir ses propositions commerciales, il vous suffit de modifier votre abonnement aux newsletters situées dans la rubrique « Mon compte » ou d'envoyer un e-mail précisant votre demande au service client des Chocolats Weiss. Nous vous confirmerons par retour la prise en compte de votre demande dans un délai maximum de deux mois, conformément aux dispositions réglementaires en vigueur.</p>
<p>Les informations collectées sont destinées uniquement à l'usage de la société Weiss, et ne seront pas communiquées à d'éventuels partenaires.</p>
 
   <ul>
      <li><u>Règlement des litiges</u></li>
    </ul>

  <p>Les présentes conditions générales de vente sont soumises au droit français. Les chocolats Weiss s'efforceront de trouver une solution commerciale et concertée pour les litiges éventuels pouvant intervenir lors du traitement de votre commande. A défaut, l'affaire sera portée devant le tribunal compétent.</p>

 <ul>
      <li><u>Propriété intellectuelle</u></li>
</ul>
<p>En application du code français de la propriété Intellectuelle et, plus généralement, des traités et accords internationaux comportant des dispositions relatives à la protection des droits d'auteurs, vous vous interdirez de reproduire pour un usage autre que privé, vendre, distribuer, émettre, diffuser, adapter, modifier, publier, communiquer intégralement ou partiellement, sous quelque forme que ce soit, les données, la présentation ou l'organisation du site ou les œuvres protégées par le droit d'auteur qui figurent sur le site internet &quot;&nbsp;<a href="http://www.chocolat-weiss.fr" _mce_href="http://www.chocolat-weiss.fr" target="_blank">www.chocolat-weiss.fr</a>&nbsp;&quot; sans autorisation écrite particulière et préalable du détenteur du droit d'auteur attaché à l'œuvre, à la présentation ou à l'organisation du site ou à la donnée reproduite.<br />
  <br />
  L'utilisateur qui dispose d'un site internet à titre personnel a la possibilité de placer sur son site un lien simple renvoyant directement à la page d'accueil du site www.chocolat-weiss.fr. Cette autorisation ne vaut pas pour autant une convention implicite d'affiliation.<br />

Directrice de la Publication&nbsp;:<br />
  Madame Clémentine Alzial<br />
  Hébergement du site&nbsp;:<br />
  Cienum<br />
  Le Millénium<br />
  1 rue de la Presse<br />
  BP 716<br />
  42950 Saint-Étienne.</p>     
  
   <ul>
      <li><u>Décharge de responsabilité</u></li>
    </ul> 
        <p>La société Chocolat <strong>Weiss</strong> n'est tenue que d'une simple obligation de moyens concernant les informations qu'elle met à disposition des personnes qui accèdent à son site Web. Alors même que nous avons effectué toutes les démarches pour nous assurer de la fiabilité des informations contenues sur ce site web, Chocolat Weiss ne peut encourir aucune responsabilité du fait d'erreurs, d'omissions, ou pour les résultats qui pourraient être obtenus par l'usage de ces informations.<br />
  <br />
  Notamment, l'usage de liens hypertextes peut conduire votre consultation de notre site vers d'autres serveurs pour prendre connaissance de l'information recherchée, serveurs sur lesquels Chocolat &nbsp;Weiss n'a aucun contrôle.</p>
  
  </div>    
  </div>   
  
   <div class="accordion_titre" headerindex="10h">Service Clients</div>
      <div class="accordion_content" contentindex="10c" style="display: none;">
                <div>
<p>Pour toute information, le service clients se tient à votre disposition par courriel à <a href="mailto:service.clients@weiss.fr" _mce_href="mailto:service.clients@weiss.fr">service.clients@weiss.fr</a>. Il est aussi possible de nous contacter par l'intermédiaire du formulaire de contact disponible dans la rubrique <a href="/contacts" _mce_href="/contacts">Contact</a>.</p>

  </div>    
  </div>   
  
  <div class="accordion_titre" headerindex="11h">Signature Électronique</div>
      <div class="accordion_content" contentindex="11c" style="display: none;">
                <div>
<p>La confirmation de votre commande par votre « double-clic », l'authentification et la protection de l'intégralité des messages constituent une signature électronique. Cette signature électronique à valeur est équivalente à une signature manuscrite entre les parties. Tout récapitulatif de commande que vous avez validé par un &quot;double-clic&quot; constitue un engagement irrévocable. Toutes les commandes font l'objet d'un e-mail de confirmation. Ce document, à conserver, constitue la preuve de votre commande et du contrat liant les parties. La SAS Weiss &nbsp;procède systématiquement à un archivage des preuves de commandes et de facturation pouvant être produits en cas de nécessité.</p>

  </div>    
  </div>   

<div class="clear"></div>
            
  </div>
</div>