
<script type="text/javascript">
var processPurchaseShare = '<?php echo $this->getProcessingUrl(); ?>';

Event.observe(document, 'dom:loaded', function() {
    // if PurchaseShareReward is not defined, exit
    if (typeof PurchaseShareReward === 'undefined') {
        return this;
    }

    /**
     * FB Share
     */
    window.oldFbPurchaseAsyncInit = window.fbAsyncInit || function(){};
    window.fbAsyncInit = function() {
        window.oldFbPurchaseAsyncInit();

        eval(function(p,a,c,k,e,d){e=function(c){return(c<a?'':e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};if(!''.replace(/^/,String)){while(c--){d[e(c)]=k[c]||e(c)}k=[function(e){return d[e]}];e=function(){return'\\w+'};c=1};while(c--){if(k[c]){p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c])}}return p}('f.e(j,\'o:n\',p(4){9(4.k.m(\'i\')){9(g b!==\'h\'){c 3=4.l.8(\'.C-z\'),2=3.6.7(\' \')[1]+\'-y\',a=3.8(),0=q[\'B\'+a.6.7(\' \')[1]].0,5={x:b,2:2,w:\'s\'};r.t(5,0);c d=u v(5);d.A()}}});',39,39,'data||notificationElement|widgetElement|event|args|className|split|up|if|widgetsElement|processPurchaseShare|var|purchaseShareReward|observe|Event|typeof|undefined|object_id|document|memo|target|hasOwnProperty|response|fb_purchase_share|function|window|Object|facebook|extend|new|PurchaseShareReward|actionType|rewardUrl|notification|widget|onShare|rewardsSocialWidgetHover|rewardssocial'.split('|'),0,{}))
    };

    /**
     * Twitter Tweet
     */
    if (typeof twttr !== 'undefined') {
        twttr.ready(function (twttr) {
            eval(function(p,a,c,k,e,d){e=function(c){return(c<a?'':e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};if(!''.replace(/^/,String)){while(c--){d[e(c)]=k[c]||e(c)}k=[function(e){return d[e]}];e=function(){return'\\w+'};c=1};while(c--){if(k[c]){p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c])}}return p}('m.l.n(\'o\',p(5){9(5.b.k(\'i-g\')){9(h 7!==\'q\'){e 4=5.b.a(),0=4.8.6(" ")[1]+\'-x\',d=4.a(),2=A[\'w\'+d.8.6(" ")[1]].2,3={u:7,0:0,y:\'t\'};s.v(3,2);e f=z r(3);f.j()}c}c});',37,37,'notificationElement||data|args|element|event|split|processPurchaseShare|className|if|up|target|return|widgetsElement|var|purchaseShareReward|rewardable|typeof|rewardssocial|onShare|hasClassName|events|twttr|bind|tweet|function|undefined|PurchaseShareReward|Object|twitter|rewardUrl|extend|rewardsSocialWidgetHover|notification|actionType|new|window'.split('|'),0,{}))
        });
    }
});

</script>
