<script type="text/javascript">

    /**
     *
     * @param rule_id
     * @return
     */
    function feignPriceChange(rule_id)
    {
        var newPrice = $(new_price_dom_id);
        var oldPrice = $(old_price_dom_id);
        var numUses = getRedemptionUses();
        if(rule_id == null) {
            rule_id = $('redemption_rule').value;
        }

        if(!show_lowest_price) { return; }

        // TODO: this should be from optionsPrice.showBothPrices
        var isShowingTwoPrices = (newPrice == null);
        if(isShowingTwoPrices) {
            var newPriceExclTax = $(new_price_excl_tax_dom_id);
            var newPriceInclTax = $(new_price_incl_tax_dom_id);
            var oldPriceExclTax = $(old_price_excl_tax_dom_id);
            var oldPriceInclTax = $(old_price_incl_tax_dom_id);
        }

        if(!isShowingTwoPrices && oldPrice == null) {        	
            oldPrice = newPrice.cloneNode(true);
            newPrice.up().insertBefore(oldPrice, newPrice);
            oldPrice.id = old_price_dom_id;
            oldPrice.removeClassName('price');
            oldPrice.addClassName('old-price');
			
			// For MC 1.9+ support,
            var extraInfoBlocks = $$('.product-view .product-shop .extra-info');
            if (extraInfoBlocks.length === 1){
            	extraInfo = extraInfoBlocks[0];
            	var newParent = new Element('div', {'class': 'price-info new-price-info'});
            	newParent.appendChild(new Element('div', {'class': 'price-box'})).appendChild(newPrice);
            	extraInfo.up().insertBefore(newParent, extraInfo.nextSibling);            	
            }
            
            do_hide_old_price = true;
        } else if (isShowingTwoPrices && oldPriceExclTax == null) {
            oldPriceExclTax = newPriceExclTax.cloneNode(true);
            newPriceExclTax.up().insertBefore(oldPriceExclTax, newPriceExclTax);
            oldPriceExclTax.id = old_price_excl_tax_dom_id;
            oldPriceExclTax.removeClassName('price');
            oldPriceExclTax.addClassName('old-price');

            oldPriceInclTax = newPriceInclTax.cloneNode(true);
            newPriceInclTax.up().insertBefore(oldPriceInclTax, newPriceInclTax);
            oldPriceInclTax.id = old_price_incl_tax_dom_id;
            oldPriceInclTax.removeClassName('price');
            oldPriceInclTax.addClassName('old-price');

            do_hide_old_price = true;
        }

        var finalPrice = getProductPriceBeforeRedemptions();

        if(rule_id == "") {
            if(do_hide_old_price) {
                if(!isShowingTwoPrices) {
                    oldPrice.hide();
                } else {
                    oldPriceExclTax.hide();
                    oldPriceInclTax.hide();
                }
            }

            optionsPrice.productPrice = finalPrice;

            var prices = reloadPricesAfterRedemptions();
            updatePriceDisplay(prices, isShowingTwoPrices, false);
        } else {
            if(do_hide_old_price) {
                if(!isShowingTwoPrices) {
                    oldPrice.show();
                } else {
                    oldPriceExclTax.show();
                    oldPriceInclTax.show();
                }
            }
            var price_disposition = rule_options[rule_id]['price_disposition'];
            var priceAdjustment = priceAdjuster(finalPrice, rule_options[rule_id]['effect']);
            
            // Recalculate adjustemnts if they are 0 (that means we are dealing with a bundle product)
            if (price_disposition == 0) {
                price_disposition = finalPrice - priceAdjustment;
            }
            //Edited 2/24/2010 7:41:46 AM : prices that set "to_fixed" discount should also
            if(rule_options[rule_id]['discount_action'] == 'by_fixed' && rule_options[rule_id]['new_price_flt'] <= 0.0000) {
                optionsPrice.productPrice = 0;
                optionsPrice.minusDisposition = 9999999999; // hack to make sure the price stays at 0;
            } else {

                if (rule_options[rule_id]['price_disposition'] == 0 && isToFixedPriceDiscount(rule_options[rule_id]['effect'])) {
                    // If we have a bundle product & a "to fixed price" type of discount
                    optionsPrice.productPrice = (numUses > 0) ? priceAdjustment : finalPrice;
                } else {
                    var discount = price_disposition * numUses;
                    optionsPrice.productPrice = finalPrice - discount;
                }

                // Magento 1.4.2 keeps optionsPrice.productPrice at the base price
                // this fix brings the price back to the base amount
                if(optionsPrice.optionPrices.config != undefined) {
                    // TODO: this if statement achieves nothing
                    if(optionsPrice.optionPrices.config.price != undefined) {
                        optionsPrice.productPrice = finalPrice - discount;
                    } else {
                        optionsPrice.productPrice = finalPrice - discount;
                    }
                }

            }

            var prices = reloadPricesAfterRedemptions();
            updatePriceDisplay(prices, isShowingTwoPrices, true, rule_id);
        }
    }
    
    // Calculate price adjustments
    function priceAdjuster(price, code)
    {
        if (code.indexOf("-") > -1) {
            if (code.indexOf("%") > -1) {
                var fx    = 1 + code.replace("%", "") / 100;
                price = price * fx;
            } else {
                price = price + code;
            }
        } else {
            if (code.indexOf("%") > -1) {
                var fx    = code.replace("%", "") / 100;
                price = price * fx;
            } else {
                price = code;
            }
        }
        
        return price;
    }
    
    // Check if we are dealing with a "To Fixed Amount" type of discount
    function isToFixedPriceDiscount(code) 
    {
        return !(code.indexOf("-") > -1 || code.indexOf("%") > -1);
    }

    function getRedemptionUses() {
        var uses;
        if(slider_mode) {
            uses = rSlider.getUses();
        } else {
            uses = $('redemption_rule_uses').value;
        }
        return (uses === "") ? 1 : parseInt(uses);
    }

    function reloadPricesAfterRedemptions()
    {
        price = parseFloat(optionsPrice.productPrice);
        priceInclTax = parseFloat(optionsPrice.productPrice) * (100 + optionsPrice.currentTax) / 100;

        if (optionsPrice.includeTax == 'true') {
            // tax = tax included into product price by admin
            var tax = price / (100 + optionsPrice.defaultTax) * optionsPrice.defaultTax;
            var excl = price - tax;
            var incl = excl*(1+(optionsPrice.currentTax/100));
        } else {
            var tax = price * (optionsPrice.currentTax / 100);
            var excl = price;
            var incl = excl + tax;
        }

        excl += parseFloat(optionsPrice.plusDisposition);
        incl += parseFloat(optionsPrice.plusDisposition);
        excl -= parseFloat(optionsPrice.minusDisposition);
        incl -= parseFloat(optionsPrice.minusDisposition);

        incl = (incl < 0) ? 0 : incl;
        excl = (excl < 0) ? 0 : excl;

        return {'includingTax': incl, 'excludingTax': excl};
    }

    function updatePriceDisplay(prices, isShowingTwoPrices, isWithPointsCaption, rule_id)
    {

        if (isShowingTwoPrices) {
            formattedPriceIncl = '';
            if (prices.includingTax > 0 || optionsPrice.displayZeroPrice) {
                formattedPriceIncl = optionsPrice.formatPrice(prices.includingTax);
            }

            formattedPriceExcl = '';
            if (prices.excludingTax > 0 || optionsPrice.displayZeroPrice) {
                formattedPriceExcl = optionsPrice.formatPrice(prices.excludingTax);
            }
        } else {
            price = optionsPrice.showIncludeTax ? prices.includingTax : prices.excludingTax;

            formattedPrice = '';
            if (price > 0 || optionsPrice.displayZeroPrice) {
                formattedPrice = optionsPrice.formatPrice(price);
            }
        }
        
        // Don't show points if the price before redemptions is 0
        // This usually happens if we are dealing with bundle product which was not yet configured
        if (getProductPriceBeforeRedemptions() == 0) {
            return;
        }

        var newPrice = $(new_price_dom_id);
        var newPriceClone = $(new_price_dom_id+'_clone');
        var newPriceExclTax = $(new_price_excl_tax_dom_id);
        var newPriceInclTax = $(new_price_incl_tax_dom_id);

        var points_with = '';
        if (isWithPointsCaption) {
            var points_amount = rule_options[rule_id]['amount'];
            var points_currency_id = rule_options[rule_id]['currency_id'];
            var points_caption = getPointsString(points_amount * getRedemptionUses(), points_currency_id);
            points_with = " " + CAPTION_WITH + " " + points_caption;
        }

        if (!isShowingTwoPrices) {
            var priceString = '&nbsp;' + formattedPrice + '<span class="using-points">' + points_with + '</span>';
            if(newPrice.down() != null && !newPrice.down().hasClassName("using-points")) {
                newPrice.down().innerHTML = priceString;
            } else if((newPrice.down() == null || newPrice.down().hasClassName("using-points")) && newPrice != null) {
                newPrice.innerHTML = priceString;
            } else { /*don't know where it is so just don't show the points thing.*/ }
        } else {
        	var priceString = '&nbsp;' + formattedPriceExcl + '<span class="using-points">' + points_with + '</span>';
            if(newPriceExclTax.down() != null && !newPriceExclTax.down().hasClassName("using-points")) {
                newPriceExclTax.down().innerHTML = priceString;
            } else if((newPriceExclTax.down() == null || newPriceExclTax.down().hasClassName("using-points")) && newPriceExclTax != null) {
                newPriceExclTax.innerHTML = priceString;
            } else { /*don't know where it is so just don't show the points thing.*/ }

            var priceString = '&nbsp;' + formattedPriceIncl + '<span class="using-points">' + points_with + '</span>';
            if(newPriceInclTax.down() != null && !newPriceInclTax.down().hasClassName("using-points")) {
                newPriceInclTax.down().innerHTML = priceString;
            } else if((newPriceInclTax.down() == null ||newPriceInclTax.down().hasClassName("using-points")) && newPriceInclTax != null) {
                newPriceInclTax.innerHTML = priceString;
            } else { /*don't know where it is so just don't show the points thing.*/ }
        }

        // TODO: use a style more akin to this for updating the values, it's much cleaner
        /*if ($(pair.value).select('.price')[0]) {
            $(pair.value).select('.price')[0].innerHTML = formattedPrice;
            if ($(pair.value+this.duplicateIdSuffix) && $(pair.value+this.duplicateIdSuffix).select('.price')[0]) {
                $(pair.value+this.duplicateIdSuffix).select('.price')[0].innerHTML = formattedPrice;
            }
        } else {
            $(pair.value).innerHTML = formattedPrice;
            if ($(pair.value+this.duplicateIdSuffix)) {
                $(pair.value+this.duplicateIdSuffix).innerHTML = formattedPrice;
            }
        }*/


        if (newPriceClone != null && newPriceClone.down() != null) {
            newPriceClone.down().innerHTML = formattedPrice;
        } else if (newPriceClone != null && newPriceClone.down() == null) {
            newPriceClone.innerHTML = formattedPrice;
        }

    }
</script>