<?php
/**
 * Category view template
 *
 * @see Mage_Catalog_Block_Category_View
 */
?>
<?php
    $_helper    = $this->helper('catalog/output');
    $_category  = $this->getCurrentCategory();
    $_imgHtml   = '';
    if ($_imgUrl = $_category->getImageUrl()) {
        $_imgHtml = '<p class="category-image"><img src="'.$_imgUrl.'" alt="'.$this->htmlEscape($_category->getName()).'" title="'.$this->htmlEscape($_category->getName()).'" /></p>';
        $_imgHtml = $_helper->categoryAttribute($_category, $_imgHtml, 'image');
    }
?>
<div class="page-title category-title">
    <?php if($this->IsRssCatalogEnable() && $this->IsTopCategory()): ?>
        <a href="<?php echo $this->getRssLink() ?>" class="link-rss"><?php echo $this->__('Subscribe to RSS Feed') ?></a>
    <?php endif; ?>
    <h1><?php echo $_helper->categoryAttribute($_category, $_category->getName(), 'name') ?></h1>
</div>

<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

<?php if($this->isContentMode()): ?>
    <?php echo $this->getCmsBlockHtml() ?>

<?php elseif($this->isMixedMode()): ?>
    <?php echo $this->getCmsBlockHtml() ?>
    <?php echo $this->getProductListHtml() ?>

<?php else: ?>
    <?php echo $this->getProductListHtml() ?>
<?php endif; ?>

<!--rajout Lr-->
<!--rajout Lr-->
<?php if($_category->getdescription_bas_categorie()): ?>
    
<div class="block-description_bas_de_page_category">
<div class="block-title_bas_de_page_category">
        <span><?php echo $this->__('En savoir plus sur ') ?><?php echo $_helper->categoryAttribute($_category, $_category->getName(), 'name') ?></span>
    </div>
     <div class="description_bas_de_page_category"><?php echo $_category->getdescription_bas_categorie(); ?></div>
	     		 </div>
				 <?php endif; ?>
 
 <!-- fin de rajout LR -->

 
 <?php  if(Mage::getModel('core/variable')->loadByCode('zanox')->getValue('plain') == 'on'): ?>
	<!-- Mastertag ZANOX -->

	<script type="text/javascript">
		var zx_category = "<?php echo $_category->getName(); ?>";
	</script>

	<!-- Start of Category Page Mastertag Code: -->
	<div class="zx_0292D39903388362E66A zx_mediaslot">
		<script type="text/javascript">
			window._zx = window._zx || [];
			window._zx.push({"id":"0292D39903388362E66A"});
			(function(d) {
				var s = d.createElement("script"); s.async = true;
				s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//static.zanox.com/scripts/zanox.js";
				var a = d.getElementsByTagName("script")[0]; a.parentNode.insertBefore(s, a);
			}(document));
		</script>
	</div>
	<!-- End of Category Page Mastertag Code -->

<?php endif; ?>
