<?php $post = $this->getPost(); ?>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="postWrapper">
    <?php
        if($banner_content = $post->getBannerContent()){
    ?>

    <div class="postBanner">
        <div class="postDate for-mobile"><div><?php echo date('j', strtotime($post->getCreatedTime())); ?><br/><?php echo date('M', strtotime($post->getCreatedTime())); ?></div></div>
        <?php echo $banner_content; ?>
    </div>
    <?php
        }
    ?>
    <div class="postDetails">
        <div class="postDate for-desktop"><div><?php echo date('j', strtotime($post->getCreatedTime())); ?><br/><?php echo date('M', strtotime($post->getCreatedTime())); ?></div></div>
        <div class="postBy"><?php echo $post->getUser(); ?></div>
        <div class="postTags"><?php echo $this->getTagsHtml($post) ?></div>
        <?php if ($this->getCommentsEnabled()): ?>
        <div class="postComments">
            <a href="<?php echo $post->getAddress(); ?>#commentBox" ><?php echo $post->getCommentCount(); ?>&nbsp;<?php echo $this->__('Comments'); ?></a>
        </div>
        <?php endif; ?>
    </div>
    <div class="postTitle">
        <h2><?php echo $post->getTitle(); ?></h2>
    </div>

    <div class="postContent"><?php echo $post->getPostContent(); ?></div>
    <?php echo $this->getBookmarkHtml($post) ?>
</div>

<!-- Comment Section -->

<?php if ($this->getCommentsEnabled()): ?>
    <?php $comments = $this->getComment(); ?>
    <div class="postTitle"><a name="commentBox" ></a>
        <h2 class="commentTitle"><?php echo $this->__('Comments') ?> (<?php echo count($comments); ?>)</h2>
    </div>

        <?php foreach ($comments as $comment) : ?>
            <div class="commentWrapper">
                <div class="commentDetails"><h4 class="username"><?php echo $comment->getUser(); ?></h4> <?php echo $this->formatDate($comment->getCreatedTime(), Mage::getStoreConfig('blog/blog/dateformat'), true); ?></div>
                <div class="commentContent"><?php echo nl2br($comment->getComment()); ?></div>
            </div>       
        <?php endforeach; ?>
     <?php echo $this->getChildHtml('trego_blog_comments_toolbar'); ?>
 

    <?php if ($post->getComments()): ?>
        <div class="postError"><?php echo Mage::helper('blog')->__('Comments are Closed for this post') ?></div>
    <?php else: ?>
        <?php if ($this->getLoginRequired()): ?>
            <?php if ($this->helper('customer')->isLoggedIn()): ?>
                <form action="" id="postComment" method="post">  
                    <fieldset class="group-select">
                        <h4 class="legend"><?php echo Mage::helper('blog')->__('Leave a Reply') ?></h4>
                        <ul class="form-list">
                            <li>
                                <div class="input-box trego-blog-comment-area">
                                    <textarea name="comment" id="comment" title="<?php echo $this->__('Comment') ?>" class="required-entry input-text" cols="50" rows="5" placeholder="<?php echo $this->__('Enter Your Comment') ?> *"><?php echo $this->getCommentText(); ?></textarea>
                                </div>
                            </li>
                        </ul>
                    </fieldset>
                    <div class="button-set">
                        <input name="post_id" type="hidden" value="<?php echo $post->getPostId(); ?>" />
                        <input name="email" type="hidden" value="<?php echo $this->htmlEscape($this->helper('blog')->getUserEmail()) ?>"/>
                        <input name="user" type="hidden" value="<?php echo $this->htmlEscape($this->helper('blog')->getUserName()) ?>"/>
                        <button class="form-button button" type="submit"><span><span><?php echo Mage::helper('blog')->__('Post Comment') ?></span></span></button>
                    </div>
                </form>

                <script type="text/javascript">
                    var contactForm = new VarienForm('postComment', false);
                </script>            

            <?php else: ?>
                <p><?php echo Mage::helper('blog')->__('You must be logged in to post a comment.'); ?></p>
                <p><a href="<?php echo Mage::helper('customer')->getLoginUrl(); ?>"><?php echo Mage::helper('blog')->__('click here'); ?></a> <?php echo Mage::helper('blog')->__('to log in'); ?></p>
            <?php endif ?>

        <?php else: ?>

            <form action="" id="postComment" method="post">
                <fieldset class="group-select">
                    <h4 class="legend"><?php echo Mage::helper('blog')->__('Leave a Reply') ?></h4>
                    <ul class="form-list">
                        <li>
                            <div class="input-box">
                                <input name="user" id="user" value="<?php echo $this->getCommentName(); ?>" title="<?php echo $this->__('Name') ?>" class="required-entry input-text" type="text" placeholder="<?php echo Mage::helper('blog')->__('Enter Your Name') ?> *" />
                            </div>

                            <div class="input-box">
                                <input name="email" id="email" value="<?php echo $this->getCommentEmail(); ?>" title="<?php echo $this->__('Email') ?>" class="required-entry input-text validate-email" type="text" placeholder="<?php echo Mage::helper('blog')->__('Enter Your Email') ?> *" />
                            </div>

                            <div class="clear"></div>

                            <div class="input-box trego-blog-comment-area">
                                <textarea name="comment" id="comment" title="<?php echo Mage::helper('blog')->__('Comment') ?>" class="required-entry input-text" cols="50" rows="5" placeholder="<?php echo Mage::helper('blog')->__('Your Comment') ?> *"><?php echo $this->getCommentText(); ?></textarea>
                            </div>
                        </li>
                    </ul>
                </fieldset>
                <div class="button-set">
                <?php
                        if (Mage::getStoreConfig('blog/recaptcha/enabled') && !$this->helper('customer')->isLoggedIn()) {
                            ?><div class="recaptcha"><?php
                require_once 'recaptcha/recaptchalib-trego.php';

                // Get a key from http://recaptcha.net/api/getkey
                $publickey = Mage::getStoreConfig('blog/recaptcha/publickey');
                $privatekey = Mage::getStoreConfig('blog/recaptcha/privatekey');
                $error = null;

                echo recaptcha_get_html($publickey, $error);
                            ?></div><?php
            }
                        ?>  
                    <input name="post_id" type="hidden" value="<?php echo $post->getPostId(); ?>" />
                    <button class="button form-button" type="submit"><span><span><?php echo Mage::helper('blog')->__('Post Comment') ?></span></span></button>
                </div>
            </form>

            <script type="text/javascript">
                var contactForm = new VarienForm('postComment', false);
            </script>
        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>
