<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
?>
<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_productCollection->addAttributeToSelect('news_from_date')
        ->addAttributeToSelect('news_to_date');
    $_helper = $this->helper('catalog/output');
	$store = Mage::app()->getStore();
	$code  = $store->getCode();
?>
<?php if(!$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<div class="category-products">
    <?php /*echo $this->getToolbarHtml() */?> 
    <?php // List mode ?>
    <?php if($this->getMode()!='grid'): ?>
    <?php $_iterator = 0; ?>
    <ol class="products-list" id="products-list">
    <?php foreach ($_productCollection as $_product): ?>
        <li class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
            <?php // Product Image ?>
            <div class="product-image-area">
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                    <?php
                        if(Mage::getStoreConfig("trego_settings/category/alternative_image", $code)){
                    ?>
                        <img class="defaultImage" src="<?php if(Mage::getStoreConfig("trego_settings/category/aspect_ratio",$code)):?><?php echo $this->helper('catalog/image')->init($_product, 'small_image')->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(350);?><?php else: ?><?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(Mage::getStoreConfig("trego_settings/category/ratio_width",$code),Mage::getStoreConfig("trego_settings/category/ratio_height",$code)); ?><?php endif; ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"/>
                       <!-- <img class="hoverImage" src="<?php if(Mage::getStoreConfig("trego_settings/category/aspect_ratio",$code)):?><?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(350);?><?php else: ?><?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')->resize(Mage::getStoreConfig("trego_settings/category/ratio_width",$code),Mage::getStoreConfig("trego_settings/category/ratio_height",$code)); ?><?php endif; ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'thumbnail'), null, true) ?>"/>-->
                    <?php
                        } else {
                    ?>
                        <img src="<?php if(Mage::getStoreConfig("trego_settings/category/aspect_ratio",$code)):?><?php echo $this->helper('catalog/image')->init($_product, 'small_image')->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(350);?><?php else: ?><?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(Mage::getStoreConfig("trego_settings/category/ratio_width",$code),Mage::getStoreConfig("trego_settings/category/ratio_height",$code)); ?><?php endif; ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"/>
                    <?php
                        }
                    ?>
                    </a>
                <?php // if($_product->getRatingSummary()): ?>
                <?php echo $this->getReviewsSummaryHtml($_product) ?>
                <?php // endif; ?>
                <div class="clearer"></div>
            </div>
            <?php // Product description ?>
            <div class="product-shop">
                <div class="f-fix">
                    <span class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></span><br />
                    <?php echo $this->getPriceHtml($_product, true) ?>
                    <div class="desc std">
                        <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                       <!-- <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>-->
                    </div>
                    <div class="links-set">
                    <?php if($_product->isSaleable()): ?>
                    <?php  if ( !($_product->getData('has_options') || $_product->isGrouped()) ) :  ?>
                        <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="<?php if(Mage::getStoreConfig("ajaxcart/addtocart/enablecategory", $code)):?>setLocationAjax('<?php echo $this->getAddToCartUrl($_product) ?>')<?php else: ?>setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')<?php endif; ?>"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                    <?php else : ?>
                        <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="<?php if(Mage::getStoreConfig("ajaxcart/addtocart/enablecategory", $code)):?>showOptions('<?php echo $_product->getId()?>')<?php else: ?>setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')<?php endif; ?>"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                        <a href='<?php echo $this->getUrl('ajaxcart/index/options',array('product_id'=>$_product->getId()));?>' class='fancybox' id='fancybox<?php echo $_product->getId()?>' style='display:none'>Options</a>
                    <?php endif;?>
                    <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                    <?php endif; ?>
                        <ul class="add-to-links">
  			<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
                            <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                <li><a href="<?php if(Mage::getStoreConfig("ajaxcart/addtolinks/enablecategory", $code)):?>javascript:ajaxWishlist('<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>','<?php echo $_product->getId()?>');<?php else: ?><?php echo $this->helper('wishlist')->getAddUrl($_product) ?><?php endif; ?>" class="link-wishlist" title="<?php echo $this->__('Add to Wishlist') ?>"><?php echo $this->__('Add to Wishlist') ?></a></li>
                            <?php endif; ?>
                            <?php /*if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                <li><a href="<?php if(Mage::getStoreConfig("ajaxcart/addtolinks/enablecategory", $code)):?>javascript:ajaxCompare('<?php echo $_compareUrl ?>','<?php echo $_product->getId()?>');<?php else: ?><?php echo $_compareUrl ?><?php endif; ?>" class="link-compare" title="<?php echo $this->__('Add to Compare') ?>"><?php echo $this->__('Add to Compare') ?></a></li>
                            <?php endif;*/ ?>
                        </ul>
                    </div>
                </div>
            </div>
        </li>
    <?php endforeach; ?>
    </ol>
    <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

    <?php else: ?>

    <?php // Grid Mode ?>

    <?php $_collectionSize = $_productCollection->count() ?>
    <?php $_columnCount = $this->getColumnCount(); ?>
        <ul class="products-grid">
    <?php $i=0; foreach ($_productCollection as $_product): ?>
            <li class="item<?php if($i==0): ?> first<?php elseif($i==$_collectionSize-1): ?> last<?php endif; ?>">
                <div class="product-image-area">
                    <span class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"></span>
                    <?php
                        if(Mage::getStoreConfig("trego_settings/category/alternative_image", $code)){
                    ?>
                        <img class="defaultImage" src="<?php if(Mage::getStoreConfig("trego_settings/category/aspect_ratio",$code)):?><?php echo $this->helper('catalog/image')->init($_product, 'small_image')->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(350);?><?php else: ?><?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(Mage::getStoreConfig("trego_settings/category/ratio_width",$code),Mage::getStoreConfig("trego_settings/category/ratio_height",$code)); ?><?php endif; ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"/>
                        <img class="hoverImage" src="<?php if(Mage::getStoreConfig("trego_settings/category/aspect_ratio",$code)):?><?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(350);?><?php else: ?><?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')->resize(Mage::getStoreConfig("trego_settings/category/ratio_width",$code),Mage::getStoreConfig("trego_settings/category/ratio_height",$code)); ?><?php endif; ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'thumbnail'), null, true) ?>"/>
                    <?php
                        } else {
                    ?>
                        <img width="" height="" src="<?php if(Mage::getStoreConfig("trego_settings/category/aspect_ratio",$code)):?><?php echo $this->helper('catalog/image')->init($_product, 'small_image')->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(350);?><?php else: ?><?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(Mage::getStoreConfig("trego_settings/category/ratio_width",$code),Mage::getStoreConfig("trego_settings/category/ratio_height",$code)); ?><?php endif; ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"/>
                    <?php
                        }
                    ?>
                    </a>
                    <?php 
                        $top_position = 10;
                        // Get the Special Price
                        $specialprice = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialPrice(); 
                        // Get the Special Price FROM date
                        $specialPriceFromDate = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialFromDate();
                        // Get the Special Price TO date
                        $specialPriceToDate = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialToDate();
                        // Get Current date
                        $today =  time();
                     
                        if ($specialprice){
                            if($today >= strtotime( $specialPriceFromDate) && $today <= strtotime($specialPriceToDate) || $today >= strtotime( $specialPriceFromDate) && is_null($specialPriceToDate)){
                                if(Mage::getStoreConfig("trego_settings/product_label/sale", $code)){
                    ?>
                                <div class="sale-product-icon" style="top: <?php echo $top_position; ?>px"><?php echo $this->__('Sale');?></div>
                    <?php       
                                $top_position += 30;
                                }
                            }
                        }
                    ?>
                    <?php
                        $now = date("Y-m-d");
                        $newsFrom= substr($_product->getData('news_from_date'),0,10);
                        $newsTo=  substr($_product->getData('news_to_date'),0,10);
                        if ($newsTo != '' || $newsFrom != ''){
                            if (($newsTo != '' && $newsFrom != '' && $now>=$newsFrom && $now<=$newsTo) || ($newsTo == '' && $now >=$newsFrom) || ($newsFrom == '' && $now<=$newsTo))
                            {
                                if(Mage::getStoreConfig("trego_settings/product_label/new", $code)){
                        ?> 
                                <div class="new-product-icon" style="top: <?php echo $top_position; ?>px"><?php echo $this->__('New');?></div>
                        <?php 
                                $top_position += 30;
                                }
                            }
                        }
                        if(Mage::getStoreConfig("trego_settings/category_grid/ratings", $code)){
                    ?>
                    <?php // if($_product->getRatingSummary()){ ?>
                    <?php echo $this->getReviewsSummaryHtml($_product, 'short'); ?>
                    <?php // } ?>
                    <?php
                        }
                        if(Mage::getStoreConfig("trego_settings/category_grid/hover_button", $code)){    
                    ?>
                    <ul class="cart-button-set">
                        <li class="first">
                            <?php  if ( !($_product->getData('has_options') || $_product->isGrouped()) ) :  ?>
                                <a href="<?php if(Mage::getStoreConfig("ajaxcart/addtocart/enablecategory", $code)):?>javascript:setLocationAjax('<?php echo $this->getAddToCartUrl($_product) ?>')<?php else: ?><?php echo $this->getAddToCartUrl($_product) ?><?php endif; ?>" class="addtocart" title="<?php echo $this->__('Add to Cart') ?>"><?php echo $this->__('Add to Cart') ?></a>
                            <?php else : ?>
                                <a href="<?php if(Mage::getStoreConfig("ajaxcart/addtocart/enablecategory", $code)):?>javascript:showOptions('<?php echo $_product->getId()?>')<?php else: ?><?php echo $this->getAddToCartUrl($_product) ?><?php endif; ?>" class="addtocart" title="<?php echo $this->__('Add to Cart') ?>"><?php echo $this->__('Add to Cart') ?></a>
                                <a href='<?php echo $this->getUrl('ajaxcart/index/options',array('product_id'=>$_product->getId()));?>' class='fancybox' id='fancybox<?php echo $_product->getId()?>' style='display:none'>Options</a>
                            <?php endif;?>
                        </li>
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                        <li><a href="<?php if(Mage::getStoreConfig("ajaxcart/addtolinks/enablecategory", $code)):?>javascript:ajaxWishlist('<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>','<?php echo $_product->getId()?>');<?php else: ?><?php echo $this->helper('wishlist')->getAddUrl($_product) ?><?php endif; ?>" class="addtowishlist" title="<?php echo $this->__('Add to Wishlist') ?>"><?php echo $this->__('Add to Wishlist') ?></a></li>
                        <?php endif; ?>
                        <?php /*if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                        <li class="last"><a href="<?php if(Mage::getStoreConfig("ajaxcart/addtolinks/enablecategory", $code)):?>javascript:ajaxCompare('<?php echo $_compareUrl ?>','<?php echo $_product->getId()?>');<?php else: ?><?php echo $_compareUrl ?><?php endif; ?>" class="addtocompare" title="<?php echo $this->__('Add to Compare') ?>"><?php echo $this->__('Add to Compare') ?></a></li>
                        <?php endif;*/ ?>
                    </ul>
                    <?php
                        }
                    ?>
                    <div class="clearer"></div>
                </div>

			  
                <span class="product-name"><a href="<?php echo $_product->getProductUrl() ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></span>
  <?php echo $this->getPriceHtml($_product, true) ?>
                <?php
                if(!Mage::getStoreConfig("trego_settings/category_grid/hover_button", $code)){
                ?>
                <?php if($_product->isSaleable()): ?>
                <?php  if ( !($_product->getData('has_options') || $_product->isGrouped() || $_product->getResource()->getAttributeRawValue($_product->getEntityId(), 'ballotin', Mage::app()->getStore()) == '1' ) ) :  ?>
                    <button type="button" title="<?php echo $this->__('Découvrir') ?>" class="button btn-cart discover-product" onclick="setLocation('<?php echo $_product->getProductUrl() ?>')"><span><span><?php echo $this->__('Découvrir'); ?></span></span></button>
                <?php else : ?>
					<?php //JL 2015-10-15
						  if($_product->getResource()->getAttributeRawValue($_product->getEntityId(), 'ballotin', Mage::app()->getStore()) == '1'): ?>
						<button type="button" class="button btn-cart discover-product discover-product-ballotin " onclick="setLocation('<?php echo $_product->getProductUrl() ?>')"><span><?php echo $this->__('Composer'); ?></span></button>
					<?php else: ?>
						<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart discover-product" onclick="<?php if(Mage::getStoreConfig("ajaxcart/addtocart/enablecategory", $code)):?>showOptions('<?php echo $_product->getId()?>')<?php else: ?>setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')<?php endif; ?>"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
						<a href='<?php echo $this->getUrl('ajaxcart/index/options',array('product_id'=>$_product->getId()));?>' class='fancybox' id='fancybox<?php echo $_product->getId()?>' style='display:none'>Options</a>
					<?php endif; ?>
                <?php endif;?>
                    
                <?php else: ?>
                    <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                <?php endif; ?>

                <ul class="add-to-links">
<a href="<?php echo $_product->getProductUrl() ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
                    <?php if ($this->helper('wishlist')->isAllow()) : ?>
                        <li><a href="<?php if(Mage::getStoreConfig("ajaxcart/addtolinks/enablecategory", $code)):?>javascript:ajaxWishlist('<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>','<?php echo $_product->getId()?>');<?php else: ?><?php echo $this->helper('wishlist')->getAddUrl($_product) ?><?php endif; ?>" class="addtowishlist" title="<?php echo $this->__('Add to Wishlist') ?>"><?php echo $this->__('Add to Wishlist') ?></a></li>
                    <?php endif; ?>
                    <?php /*if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                        <li class="last"><a href="<?php if(Mage::getStoreConfig("ajaxcart/addtolinks/enablecategory", $code)):?>javascript:ajaxCompare('<?php echo $_compareUrl ?>','<?php echo $_product->getId()?>');<?php else: ?><?php echo $_compareUrl ?><?php endif; ?>" class="addtocompare" title="<?php echo $this->__('Add to Compare') ?>"><?php echo $this->__('Add to Compare') ?></a></li>
                    <?php endif;*/ ?>
                </ul>
                <?php
                }
                ?>
                <?php $i++; ?>
            </li>
        <?php endforeach ?>
        </ul>
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
    <?php endif; ?>
        <div class="category-right">
        <?php
            echo $this->getChildHtml("category-right");
        ?>
        </div>
    <div class="toolbar-bottom">
        <?php echo $this->getToolbarHtml() ?>
    </div>
    <script type="text/javascript">
    jQuery(document).ready(function(){
        jQuery('.products-grid li:nth-child(3n)').addClass('nth-child-3n');
        jQuery('.products-grid li:nth-child(3n+1)').addClass('nth-child-3np1');
        jQuery('.products-grid li:nth-child(2n)').addClass('nth-child-2n');
        jQuery('.products-grid li:nth-child(2n+1)').addClass('nth-child-2np1');
<?php
    if(Mage::getStoreConfig("trego_settings/category_grid/hover_effect", $code)){    
?>
        var ishover = false;
        jQuery('.col-main .products-grid li.item').mouseenter(function(){
            if(!ishover){
                jQuery('.col-main .products-grid li.item').css({
                    'marginRight':'',
                    'marginLeft':'',
                    'marginTop':'',
                    'marginBottom':'',
                    'paddingRight':'',
                    'paddingLeft':'',
                    'paddingTop':'',
                    'paddingBottom':'',
                    'zIndex':'1',
                    'border-radius':'',
                    'box-shadow' : '',
                    '-moz-box-shadow' : '',
                    '-webkit-boxshadow' : '',
                    'backgroundColor' : 'transparent'

                });
                jQuery(this).css('marginRight', (parseFloat(jQuery(this).css('marginRight').replace('px', ''))-8)+"px");
                jQuery(this).css('marginLeft', (parseFloat(jQuery(this).css('marginLeft').replace('px', ''))-8)+"px");
                jQuery(this).css('marginTop', (parseFloat(jQuery(this).css('marginTop').replace('px', ''))-8)+"px");
                //jQuery(this).css('marginBottom', (parseFloat(jQuery(this).css('marginBottom').replace('px', ''))-8)+"px");
                jQuery(this).css('paddingRight', (parseFloat(jQuery(this).css('paddingRight').replace('px', ''))+8)+"px");
                jQuery(this).css('paddingLeft', (parseFloat(jQuery(this).css('paddingLeft').replace('px', ''))+8)+"px");
                jQuery(this).css('paddingTop', (parseFloat(jQuery(this).css('paddingTop').replace('px', ''))+8)+"px");
                //jQuery(this).css('paddingBottom', (parseFloat(jQuery(this).css('paddingBottom').replace('px', ''))+8)+"px");
                jQuery(this).css('backgroundColor', '#f1f1f1');
                jQuery(this).css('zIndex', '2');
                jQuery(this).css({
                    'border-radius' : '5px',
                    'box-shadow' : '0px 0px 5px #888',
                    '-moz-box-shadow' : '0px 0px 5px #888',
                    '-webkit-boxshadow' : '0px 0px 5px #888'
                });
                ishover = true;
            }
        }).mouseleave(function(){
            jQuery(this).css({
                'marginRight':'',
                'marginLeft':'',
                'marginTop':'',
                'marginBottom':'',
                'paddingRight':'',
                'paddingLeft':'',
                'paddingTop':'',
                'paddingBottom':'',
                'zIndex':'1',
                'border-radius':'',
                'box-shadow' : '',
                '-moz-box-shadow' : '',
                '-webkit-boxshadow' : '',
                'backgroundColor' : 'transparent'

            });
            ishover = false;
        });
<?php
    }
?>
    });
    </script>
</div>
<?php endif; ?>