<?php if( $this->getCollection() && $this->count()): ?>
<div class="block">
    <div class="block-title">
        <strong><span><?php echo $this->__('My Recent Reviews') ?></span></strong>
    </div>
    <div class="block-content">
        <a href="<?php echo $this->getAllReviewsUrl() ?>"><?php echo $this->__('View All Reviews') ?></a>
        <ol id="my_recent_reviews">
        <?php $iterator = 0 ?>
        <?php foreach ($this->getCollection() as $_review): ?>
            <li class="item">
                <div class="details">
                    <h3 class="product-name"><a href="<?php echo $this->getReviewUrl($_review->getReviewId()) ?>"><?php echo $this->htmlEscape($_review->getName()) ?></a></h3>
                    <?php if($_review->getSum()): ?>
                        <div class="ratings">
                            <strong><?php echo $this->__('Rating:') ?></strong>
                            <div class="rating-box">
                                <div class="rating" style="width:<?php echo ( $_review->getSum() / $_review->getCount() ) ?>%;"></div>
                            </div>
                        </div>
                    <?php endif; ?>
                </div>
            </li>
        <?php endforeach; ?>
        </ol>
        <script type="text/javascript">decorateList('my_recent_reviews');</script>
    </div>
</div>
<?php endif; ?>
