<?php
$store = Mage::app()->getStore();
$code  = $store->getCode();
$baseURL = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);
?>
<div class="footer-container">
    <div class="footer">
        <div class="col6-set static-blocks-6">
                <div class="one-static-block">
                    <img src="<?php echo $baseURL . 'frontend/trego2016/trego/images/Reassurance_EPV1.png';  ?>" alt="">
                    <p><strong><?php echo $this->__("Entreprise du"); ?></strong><br /><?php echo $this->__("Patrimoine Vivant"); ?></p>
                </div>
                <div class="one-static-block">
                    <img src="<?php echo $baseURL . 'frontend/trego2016/trego/images/Reassurance_beurrecacao.png';  ?>" alt="">
                    <p><strong> 100%</strong><br /><?php echo $this->__("beurre de cacao"); ?></p>
                </div>
                <div class="one-static-block">
                    <img src="<?php echo $baseURL . 'frontend/trego2016/trego/images/Reassurance_sansOGM.png';  ?>" alt="">
                    <p><strong><?php echo $this->__("Sans OGM,"); ?></strong><br /><?php echo $this->__("ni huile de palme"); ?></p>
                </div>
                <div class="one-static-block">
                    <img src="<?php echo $baseURL . 'frontend/trego2016/trego/images/Reassurance_commanderapide.png';  ?>" alt="">
                    <p><strong><?php echo $this->__("Passez votre commande"); ?></strong><br /><?php echo $this->__("en 2 minutes"); ?></p>
                </div>
                <div class="one-static-block">
                    <img src="<?php echo $baseURL . 'frontend/trego2016/trego/images/Reassurance_livraison.png';  ?>" alt="">
                    <p><strong><?php echo $this->__("Choisissez votre"); ?></strong><br /><?php echo $this->__("date de livraison"); ?></p>
                </div>
                <div class="one-static-block">
                    <img src="<?php echo $baseURL . 'frontend/trego2016/trego/images/Reassurance_satisfaction.png';  ?>" alt="">
                    <p><strong><?php echo $this->__("Notre priorité"); ?></strong><br /><?php echo $this->__("votre satisfaction"); ?></p>
                </div>
        </div>
        
        <?php
//            var_dump();
        ?>
        
        <div class="col2-set newsletter-wrapper">
            <div class="newsletter col-1">
                <h2 class="newsletter-title"><?php echo $this->__('Newsletter') ?></h2>
                <?php
                if(Mage::getStoreConfig("trego_settings/footer/newsletter", $code)){
                    echo $this->getChildHtml('newsletter');
                }
                ?>
            </div>
            <div class="nugget  col-2">
                <img class="nugget-lg" src="<?php echo $baseURL . 'frontend/trego2016/trego/images/weiss_static_block.jpg';  ?>" alt="">
                <img class="nugget-mob" src="<?php echo $baseURL . 'frontend/trego2016/trego/images/nugget-mob-bg.jpg';  ?>" alt="">
                <div class="nugget-text">
                    <h2><?php echo $this->__('cumulez des pépites  !') ?></h2>
                    <p><?php echo $this->__('1€ dépensé') ?></p>
                    <p><span><?php echo $this->__('= 1 pépite') ?>&nbsp;</span><?php echo $this->__('dans votre compte!') ?></p>
                </div>
            </div>
        </div>

        <div class="col4-set">
            <div class="col-1">
                <div class="footer-title"><?php echo $this->__('À propos') ?></div>
                <div class="footer-links">
                    <?php echo $this->getChildHtml('cms_footer_links') ?>
                    <?php /*echo $this->getChildHtml('footer_links') */?>
                </div>
            </div>
	<div class="col-2">
                <div class="footer-title"><?php echo $this->__('Contactez-nous') ?></div>

                <div><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_contacts_phone')->toHtml() ?></div>

            </div>
            <div class="col-3">
                <div class="footer-title"><?php echo $this->__('Ecrivez-nous') ?></div>
                <div class="footer-links">
                <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_write_us')->toHtml() ?>

                 
                <!--  Display language switcher  -->
                <div class="lang-selector-lg">
                    <?php   echo $this->getChildHtml('store_language') ?>
                </div>                                    
                </div>          
            </div>
            <div class="col-4">
                <div class="footer-title"><?php echo $this->__('Nos boutiques') ?></div>
                <div class="footer-links">
                    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_our_shops')->toHtml() ?>
<!--                    <div class="contact-info">-->
<!--                    --><?php //echo $this->getChildHtml('cms_footer_contact') ?>
<!--                    </div>-->
                </div>
            </div>    
            <div class="lang-selector-sm">
                    <?php   echo $this->getChildHtml('store_language') ?>                
            </div>
        </div>
<!--        <div class="footer-menu">-->
            <?php // echo $this->getChildHtml('topLinks') ?>
            <?php // echo $this->getChildHtml('footer_socialIcons'); ?>
            <?php  // echo $this->getChildHtml('footer_copyrights'); ?>
<!--        </div>-->

    </div>
    <div class="footer-bottom">
        &copy; <?php echo date("Y") ?><?php echo $this-> __('Chocolat Weiss. Tous droits réservés') ?>
    </div>
    <a href="#" id="scroll-to-top">&nbsp;</a>
    <script type="text/javascript">
        var windowScroll_t;
        jQuery(window).scroll(function(){
            
            clearTimeout(windowScroll_t);
            windowScroll_t = setTimeout(function() {
                                        
                if (jQuery(this).scrollTop() > 100)
                {
                    jQuery('#scroll-to-top').fadeIn();
                }
                else
                {
                    jQuery('#scroll-to-top').fadeOut();
                }
            
            }, 500);
            
        });
        
        jQuery('#scroll-to-top').click(function(){
            jQuery("html, body").animate({scrollTop: 0}, 600, "easeOutCubic");
            return false;
        });
        
        
      
        
    </script>    
</div>



    
    
   