<?php
    //  Set visit page cookie counter
        Mage::getModel('core/cookie')->set('count_mage', isset($_COOKIE['count_mage']) ? ++$_COOKIE['count_mage'] : 1);
        $visitCount = $_COOKIE['count_mage'];    
?>  
<?php // echo $_SERVER['HTTP_HOST'] ?>
<?php $baseURL = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>
<?php $cookie = Mage::getSingleton('core/cookie'); ?>
<div class="header-container">
    <div class="header">
        <div class="header-bground">
            <div class="header-sidebar">
                <?php if ($this->getIsHomePage()):?>
                <p class="logo"><strong><?php echo $this->getLogoAlt() ?></strong><a href="<?php echo $this->getUrl('',  array('_secure' =>  Mage::app()->getFrontController()->getRequest()->isSecure())) ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><img width="150" height="150" src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a>
                <?php else:?>
                <a href="<?php echo $this->getUrl('',  array('_secure' =>  Mage::app()->getFrontController()->getRequest()->isSecure())) ?>la-maison" title="<?php echo $this->getLogoAlt() ?>" class="logo"><strong><?php echo $this->getLogoAlt() ?></strong>
                    <img class="logo-dt"  src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" />
                    <img class="logo-mobile" src="<?php echo $baseURL . 'frontend/trego2016/trego/images/logo-sm.png';  ?>" alt="<?php echo $this->getLogoAlt() ?>">
                </a>
                <?php endif?>
                <div class="box-scroll">
                    <div class="accordion-menu-trigger">
                        <div class="trigger-icon">
                            <img src="<?php echo $baseURL . 'frontend/trego2016/trego/images/menu-trigger-md.png';  ?>" alt="">
                            <img src="<?php echo $baseURL . 'frontend/trego2016/trego/images/menu-md-close.png';  ?>" alt="">
                            <!--<img class="mob-men-open" src="<?php echo $baseURL . 'frontend/trego2016/trego/images/mob-menu.png';  ?>" alt="">-->
                            <span class="trigger-text"><?php echo $this->__('Menu'); ?></span>
                        </div>
                    </div>
                    
                        <?php  echo $this->getChildHtml('topMenu'); ?>
                       <?php   echo $this->getChildHtml('topSearch'); ?>
                    <div class="clear"></div>
                    <?php  echo $this->getChildHtml('topSpecialMenu'); ?>
                    <div class="clear"></div>
                </div>
                <?php echo $this->getChildHtml('socialIcons'); ?>
                <?php // echo $this->getChildHtml('copyrights'); ?>
            </div>
            <!---<a href="javascript:void(0)" class="filterproducts-link">&nbsp;</a>-->
        </div>
		
        <div class="header-topbar">
		
<!--modif adista-->
               <?php /*echo $this->getLayout()->createBlock('cms/block')->setBlockId('bandeau_haut')->toHtml();*/ ?>

<!-- modif adista*-->

            <div class="quick-access">
					

                <?php echo $this->getChildHtml('store_language') ?>
                <?php echo $this->getChildHtml('custom_currency_selector') ?>
                <?php echo $this->getChildHtml('cart_cartheader') ?>
            </div>
<!--modif wEISS lr 20/02-->
           <!-- <h1 class="page-title"></h1>--->
<!--modif wEISS lr 20/02-->
			<div class="menu-weiss">
			<ul class="links">
			<li class="first"><a title="<?php echo $this->__('Mon Compte'); ?>" href="/customer/account/"><?php echo $this->__('Mon Compte'); ?></a></li>
			<li><a class="top-link-checkout" title="<?php echo $this->__('Commander'); ?>" href="/checkout/"><?php echo $this->__('Commander'); ?></a></li>
			<li><a class="top-link-blog" title="<?php echo $this->__('La Maison'); ?>" href="/la-maison/chocolaterie-weiss/"><?php echo $this->__('La Maison'); ?></a></li>
			<li><a class="top-link-contact" title="<?php echo $this->__('Contact'); ?>" href="/la-maison/nous-contacter"><?php echo $this->__('Contact'); ?></a></li>

				<?php if(Mage::getSingleton('customer/session')->isLoggedIn()) : ?>
					<li class=" last"><a title="<?php echo $this->__('Logout'); ?>" href="/customer/account/logout/"><?php echo $this->__('Logout'); ?></a></li>
				<?php else: ?>
					<li class=" last"><a title="<?php echo $this->__('Login'); ?>" href="/customer/account/login/"><?php echo $this->__('Login'); ?></a></li>
				<?php endif; ?>
				</ul><!-- fermeture ul bandeau_haut-->
		</div>
            <?php echo $this->getChildHtml('topContainer'); ?>
            <div class="clearer"></div>
        </div>
        <div class="filterproducts-overlay" style="display: none; position: fixed; z-index: 98; width: 100%; height: 100%; left: 0; top: 0;"></div>
        <div class="filterproducts col1-layout" style="display: none;">
            <ul class="special_menu">
            <?php
                $store = Mage::app()->getStore();
                $code  = $store->getCode();
                $enable = Mage::getStoreConfig('filterproducts/new/active',$code);
                if($enable == 1){
            ?>
                <li><a href="javascript:void(0)" class="a_latest"><span><?php echo $this->__('Latest'); ?></span><span class="expander">&nbsp;</span></a></li>
            <?php
                }
                $enable = Mage::getStoreConfig('filterproducts/featured/active',$code);
                if($enable == 1){
            ?>
                <li><a href="javascript:void(0)" class="a_featured"><span><?php echo $this->__('Featured'); ?></span><span class="expander">&nbsp;</span></a></li>
            <?php
                }
                $enable = Mage::getStoreConfig('filterproducts/special/active',$code);
                if($enable == 1){
            ?>
                <li><a href="javascript:void(0)" class="a_special"><span><?php echo $this->__('Specials'); ?></span><span class="expander">&nbsp;</span></a></li>
            <?php
                }
            ?>
            </ul>
            <a href="javascript:void(0)" class="close">Close</a>
            <span class="page-controls">
                <a href="javascript:void(0)" class="page-prev">Prev</a>
                <a href="javascript:void(0)" class="page-next">Next</a>
            </span>
            <?php echo $this->getChildHtml('filterproducts');?>
        </div>
        <script type="text/javascript">
            jQuery(document).ready(function(){
                jQuery('.header-topbar h1.page-title').html(jQuery('.main .page-title h1').html());
                /*
                if(jQuery(window).width()>1007){
                    jQuery('.box-scroll').niceScroll({zindex : 51, objfixed: true});
                }
                */
                
				/*jQuery('html').niceScroll({zindex : 9999}); */
                var ajax_loaded1 = false;
                var ajax_loaded2 = false;
                var ajax_loaded3 = false;

                jQuery('.a_latest').click(function(){
                    if(!jQuery(this).hasClass('active')){
                        jQuery('div.filterproducts').children('div').hide();
                        jQuery('.filterproducts').css('left', ((jQuery(window).width()-760)/2)+"px");
                        jQuery('div.filterproducts').children('div').removeClass('active');
                        jQuery('div#new_products').addClass('active');
                        jQuery('div#new_products').fadeIn();
                        jQuery('div.filterproducts').fadeIn();
                        jQuery('div.filterproducts-overlay').fadeIn();
                        jQuery('.special_menu li a').removeClass('active');
                        jQuery('.a_latest').addClass('active');
                        if(!ajax_loaded1){
                            jQuery.ajax({
                                url: "<?php echo $this->getUrl('filterproducts/index/newproduct',  array('_secure' =>  Mage::app()->getFrontController()->getRequest()->isSecure())) ?>",
                                context: document.body
                            }).done(function(msg) {
                                jQuery('div#new_products').html(msg);
                                ajax_loaded1 = true;
                                if(jQuery(window).height() < 925 ){
                                    jQuery('.filterproducts div.category-products').css('height', '394px');
                                    jQuery('.filterproducts').css('top', ((jQuery(window).height()-479)/2)+"px");
                                } else {
                                    jQuery('.filterproducts div.category-products').css('height', '788px');
                                    jQuery('.filterproducts').css('top', ((jQuery(window).height()-873)/2)+"px");
                                }
                            });
                        }
                    }
                });
                jQuery('.a_featured').click(function(){
                    if(!jQuery(this).hasClass('active')){
                        jQuery('div.filterproducts').children('div').hide();
                        jQuery('.filterproducts').css('left', ((jQuery(window).width()-760)/2)+"px");
                        jQuery('div.filterproducts').children('div').removeClass('active');
                        jQuery('div#featured_products').addClass('active');
                        jQuery('div#featured_products').fadeIn();
                        jQuery('div.filterproducts').fadeIn();
                        jQuery('div.filterproducts-overlay').fadeIn();
                        jQuery('.special_menu li a').removeClass('active');
                        jQuery('.a_featured').addClass('active');
                        if(!ajax_loaded2){
                            jQuery.ajax({
                                url: "<?php echo $this->getUrl('filterproducts/index/featured',  array('_secure' =>  Mage::app()->getFrontController()->getRequest()->isSecure())) ?>",
                                context: document.body
                            }).done(function(msg) {
                                jQuery('div#featured_products').html(msg);
                                ajax_loaded2 = true;
                                if(jQuery(window).height() < 925 ){
                                    jQuery('.filterproducts div.category-products').css('height', '394px');
                                    jQuery('.filterproducts').css('top', ((jQuery(window).height()-479)/2)+"px");
                                } else {
                                    jQuery('.filterproducts div.category-products').css('height', '788px');
                                    jQuery('.filterproducts').css('top', ((jQuery(window).height()-873)/2)+"px");
                                }
                            });
                        }
                    }
                });
                jQuery('.a_special').click(function(){
                    if(!jQuery(this).hasClass('active')){
                        jQuery('div.filterproducts').children('div').hide();
                        jQuery('.filterproducts').css('left', ((jQuery(window).width()-760)/2)+"px");
                        jQuery('div.filterproducts').children('div').removeClass('active');
                        jQuery('div#special_product').addClass('active');
                        jQuery('div#special_product').fadeIn();
                        jQuery('div.filterproducts').fadeIn();
                        jQuery('div.filterproducts-overlay').fadeIn();
                        jQuery('.special_menu li a').removeClass('active');
                        jQuery('.a_special').addClass('active');
                        if(!ajax_loaded3){
                            jQuery.ajax({
                                url: "<?php echo $this->getUrl('filterproducts/index/special',  array('_secure' =>  Mage::app()->getFrontController()->getRequest()->isSecure())) ?>",
                                context: document.body
                            }).done(function(msg) {
                                jQuery('div#special_product').html(msg);
                                ajax_loaded3 = true;
                                if(jQuery(window).height() < 925 ){
                                    jQuery('.filterproducts div.category-products').css('height', '394px');
                                    jQuery('.filterproducts').css('top', ((jQuery(window).height()-479)/2)+"px");
                                } else {
                                    jQuery('.filterproducts div.category-products').css('height', '788px');
                                    jQuery('.filterproducts').css('top', ((jQuery(window).height()-873)/2)+"px");
                                }
                            });
                        }
                    }
                });
                jQuery('.filterproducts-link').click(function(){ jQuery('.a_latest').click(); });
                jQuery('.filterproducts a.close').click(function(){
                    jQuery('div.filterproducts').children('div').fadeOut();
                    jQuery('div.filterproducts').fadeOut();
                    jQuery('div.filterproducts-overlay').fadeOut();
                    jQuery('.special_menu li a').removeClass('active');
                });
                jQuery('div.filterproducts-overlay').click(function(){
                    jQuery('div.filterproducts').children('div').fadeOut();
                    jQuery('div.filterproducts').fadeOut();
                    jQuery('div.filterproducts-overlay').fadeOut();
                    jQuery('.special_menu li a').removeClass('active');
                });
                var scrollHeight = 788;
                
                if(jQuery(window).height() < 925){
                    jQuery('.filterproducts div.category-products').css('height', '394px');
                    jQuery('.filterproducts').css('top', ((jQuery(window).height()-479)/2)+"px");
                    scrollHeight = 394;
                } else {
                    jQuery('.filterproducts div.category-products').css('height', '788px');
                    scrollHeight = 788
                    jQuery('.filterproducts').css('top', ((jQuery(window).height()-873)/2)+"px");
                }
                jQuery(window).resize(function(){
                    jQuery('.filterproducts').css('left', ((jQuery(window).width()-760)/2)+"px");
                    if(jQuery(window).height() < 925 ){
                        jQuery('.filterproducts div.category-products').css('height', '394px');
                        scrollHeight = 394;
                        jQuery('.filterproducts').css('top', ((jQuery(window).height()-479)/2)+"px");
                    } else {
                        jQuery('.filterproducts div.category-products').css('height', '788px');
                        scrollHeight = 788
                        jQuery('.filterproducts').css('top', ((jQuery(window).height()-873)/2)+"px");
                    }
                    if(jQuery(window).width() < 768){
                        jQuery('.filterproducts a.close').click();
                    }
                    /** for SAMSUNG GALAXY TABLET */
                    if(jQuery(window).width()>=768 && jQuery(window).width()<=1024){
                        jQuery('.header-container').css('width', jQuery(window).width()+"px");
                    } else {
                        jQuery('.header-container').css('width', '');
                    }
                    /** for SAMSUNG GALAXY TABLET */
                });
                jQuery('.filterproducts a.page-next').click(function(){
                    jQuery(".filterproducts div.active div.category-products").animate({scrollTop: jQuery(".filterproducts div.active div.category-products").scrollTop()+scrollHeight}, 600, "easeOutCubic");
                    return false;
                });
                jQuery('.filterproducts a.page-prev').click(function(){
                    jQuery(".filterproducts div.active div.category-products").animate({scrollTop: jQuery(".filterproducts div.active div.category-products").scrollTop()-scrollHeight}, 600, "easeOutCubic");
                    return false;
                });
                jQuery("html").click(function(){
                    if(jQuery(window).width()<=1024){
                        jQuery("#nav li span.plus").each(function(){
                            jQuery(this).removeClass('expanded');
                            jQuery(this).parent().removeClass('expanded');
                            jQuery(this).parent().children('ul').slideUp('fast');
                        });
                    }
                });

            });
        </script>
    </div>
</div>
    <?php $site = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB) ?>
        <!--  Display Newsletter modal at the third visit  -->

        <div data-remodal-id="<?php if($visitCount == 3 && !isset($_COOKIE['hide_newsletter'])): ?>modal-mage<?php endif; ?>" class="newsletter-modal">

                <div class="top span-12">
                    <button data-remodal-action="close" class="remodal-close"><img src="<?php echo $baseURL . 'frontend/trego2016/trego/images/pupin-close.jpg';  ?>" alt=""></button>
                </div>
                <div class="span-12  span-m-6 span-s-12 column newsletter">
                    <div class="block block-subscribe">
                        <h2 class="newsletter-title"><?php echo $this->__("Newsletter"); ?></h2>
                        <p class="newsletter-message" style="display: none;"></p>                       
                        <form action="<?php echo $site; ?>newsletter/subscriber/new/" method="post" id="newsletter-validate-detail">
                            <div class="block-content">
                                <div class="form-subscribe-header span-12">
                                    <label for="newsletter"><?php echo $this->__("Renseignez votre adresse e-mail et soyez informé des dernières actualités chocolatées Weiss.") ?><br /><span><?php echo $this->__("100 pépites offertes, soit 2€ de réduction sur votre prochaine commande !"); ?></span></label>
                                </div>
                                <div class="span-5 input-fields-container">
                                    <div class="input-box span-9">
                                        <input type="email" name="email" id="newsletter" title="<?php echo $this->__("Inscrivez-vous à notre newsletter"); ?>" class="input-text required-entry validate-email" placeholder="">
                                    </div>
                                    <div class="actions span-3">
                                        <button type="submit" title="<?php echo $this->__("Subscribe"); ?>" class="button"  ><span><span><?php echo $this->__("Ok"); ?></span></span></button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <script type="text/javascript">
                //<![CDATA[
                if(jQuery('[data-remodal-id=modal-mage]').length > 0) {
                    jQuery('[data-remodal-id=modal-mage]').remodal().open();
                    jQuery('.newsletter-modal .remodal-close').on('click',function(){                        
                        document.cookie = 'hide_newsletter=noNewsletter; path=/';                       
                    }); 
                }
                
                    

                //]]>
            </script>
        <?php // endif; ?>
<?php echo $this->getChildHtml('topcart'); ?>