<ul class="special_menu">
<?php
    $store = Mage::app()->getStore();
    $code  = $store->getCode();
    $enable = Mage::getStoreConfig('filterproducts/new/active',$code);
    if($enable == 1){
?>
    <li><a href="javascript:void(0)" class="a_latest"><span><?php echo Mage::getStoreConfig('filterproducts/new/menu',$code); ?></span><span class="expander">&nbsp;</span></a></li>
<?php
    }
    $enable = Mage::getStoreConfig('filterproducts/featured/active',$code);
    if($enable == 1){
?>
    <li><a href="javascript:void(0)" class="a_featured"><span><?php echo Mage::getStoreConfig('filterproducts/featured/menu',$code); ?></span><span class="expander">&nbsp;</span></a></li>
<?php
    }
    $enable = Mage::getStoreConfig('filterproducts/special/active',$code);
    if($enable == 1){
?>
    <li><a href="javascript:void(0)" class="a_special"><span><?php echo Mage::getStoreConfig('filterproducts/special/menu',$code); ?></span><span class="expander">&nbsp;</span></a></li>
<?php
    }
?>
</ul>
