<div class="page-title">
    <h1><?php echo $this->__('Forgot Your Password?') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->getUrl('*/*/forgotpasswordpost') ?>" method="post" id="form-validate">
    <div class="block block-forgot-password">
        <div class="block-title">
            <strong><span><?php echo $this->__('Retrieve your password here') ?></span></strong>
        </div>
        <div class="block-content">
            <p><?php echo $this->__('Please enter your email address below. You will receive a link to reset your password.') ?></p>
            <ul class="form-list">
                <li class="wide">
                    <div class="input-box">
                        <input type="text" name="email" alt="email" id="email_address" class="input-text required-entry validate-email" value="<?php echo $this->htmlEscape($this->getEmailValue()) ?>" placeholder="<?php echo $this->__('Email Address') ?> *" />
                    </div>
                </li>
                <?php echo $this->getChildHtml('form.additional.info'); ?>
            </ul>
        </div>
    </div>
    <div class="buttons-set">
        <p class="back-link"><a href="<?php echo $this->helper('customer')->getLoginUrl() ?>"><small>&laquo; </small><?php echo $this->__('Back to Login') ?></a></p>
        <button type="submit" title="<?php echo $this->__('Submit') ?>" class="button"><span><span><?php echo $this->__('Submit') ?></span></span></button>
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
//]]>
</script>
