<?php
$store = Mage::app()->getStore();
$code  = $store->getCode();
$_quickview = Mage::getStoreConfig('quickview/viewsetting/enableview',$code);
?>

<script type="text/javascript">
	var data = "";
	var active = false;
	jQuery(function($){
		if($('body').find('#resultLoading').attr('id') != 'resultLoading'){
		$('.main').append('<div id="resultLoading" style="display:none"><div><img src="<?php echo $this->loadingImage ?>"><div><?php echo $this->loadingText ?></div></div><div class="bg"></div></div>');}
		var height = $('.main').outerHeight();
		var width = $('.main').outerWidth();
		$('.ui-slider-handle').css('cursor','pointer');
		
		$('#resultLoading').css({
			'width':'100%',
			'height':'100%',
			'position':'fixed',
			'z-index':'10000000',
			'top':'0',
			'left':'0'
		});	
		$('#resultLoading .bg').css({
			'background':'<?php echo $this->overlayColor; ?>',
			'opacity':'<?php echo $this->overlayOpacity ?>',
			'width':'100%',
			'height':'100%',
			'position':'absolute',
			'top':'0'
		});
		$('#resultLoading>div:first').css({
			'width': '100%',
			'text-align': 'center',
			'position': 'absolute',
			'left': '0',
			'top': '50%',
			'font-size':'16px',
			'z-index':'10',
			'color':'<?php echo $this->loadingTextColor ?>'
			
		});
		
		<?php if($this->ajaxLayered): ?>
        $('.block-layered-nav a').on('click', function(e){sliderAjax($(this).attr('href'));e.preventDefault();});    
        <?php endif; ?>
        
        
        <?php if($this->ajaxToolbar): ?>
        $('.toolbar a').on('click', function(e){if(!$(this).hasClass('sbToggle') && !$(this).hasClass('sbSelector') && !$(this).parent().parent().hasClass('sbOptions')){var url=$(this).attr('href');sliderAjax(url);e.preventDefault()}});
        $('.toolbar select').removeAttr('onchange');
        $('.toolbar select').on('change', function(e){var url=$(this).val();sliderAjax(url);e.preventDefault()});
        <?php endif; ?>
		
		
	});

<?php if($this->ajaxSlider || $this->ajaxLayered): ?>
/*DONOT EDIT THIS CODE*/
function sliderAjax(url) {
    if (!active) {
        active = true;
        jQuery(function($) {
            oldUrl = url;
            $('#resultLoading .bg').height('100%');
            $('#resultLoading').fadeIn(300);
            try {
                $('body').css('cursor', 'wait');
                $.ajax({
                    url: url,
                    dataType: 'json',
                    type: 'post',
                    data: data,
                    success: function(data) {
						callback();
                        if (data.viewpanel) {
                            if ($('.block-layered-nav')) {
                                $('.block-layered-nav').empty();
                                $('.block-layered-nav').append(data.viewpanel)
                            }
                        }
                        if (data.productlist) {
                            $('.col-main .category-products').empty();
                            $('.col-main .category-products').append(data.productlist)
                        }
                        var hist = url.split('?');
                        if(window.history && window.history.pushState){
							window.history.pushState('GET', data.title, url);
						}
                        $('body').find('.toolbar select').removeAttr('onchange');
                        $('#resultLoading .bg').height('100%');
                        $('#resultLoading').fadeOut(300);
                        $('body').css('cursor', 'default');
                        <?php if($this->ajaxLayered): ?>
                        $('.block-layered-nav a').on('click', function(e){sliderAjax($(this).attr('href'));e.preventDefault();});    
                        <?php endif; ?>
                        
                        
                        <?php if($this->ajaxToolbar): ?>
                        $('.toolbar a').on('click', function(e){if(!$(this).hasClass('sbToggle') && !$(this).hasClass('sbSelector') && !$(this).parent().parent().hasClass('sbOptions')){var url=$(this).attr('href');sliderAjax(url);e.preventDefault()}});
                        $('.toolbar select').removeAttr('onchange');
                        $('.toolbar select').on('change', function(e){var url=$(this).val();sliderAjax(url);e.preventDefault()});
                        <?php endif; ?>
<?php if($_quickview): ?>
jQuery.noConflict();
jQuery(function($) {
    var myhref,qsbtt;
    var opt = {
        itemClass : ['.products-grid li.item', '.products-grid li.item div.item-content', '.products-list li.item', '.filter-products .products div.item'],
        aClass : 'a.product-image',
        imgClass: '.product-image img'
    };

    function ieVersion(){
        var value = -1;
        if (navigator.appName == 'Microsoft Internet Explorer'){
            var agent = navigator.userAgent;
            var reg  = new RegExp("MSIE ([0-9]{1,}[\.0-9]{0,})");
            if (reg.exec(agent) != null)
                value = parseFloat( RegExp.$1 );
        }
        return value;
    }

    function readHref(){
        var mypath = arguments[0];
        var patt = /\/[^\/]{0,}$/ig;
        if(mypath[mypath.length-1]=="/"){
            mypath = mypath.substring(0,mypath.length-1);
            return (mypath.match(patt)+"/");
        }
        return mypath.match(patt);
    }

    function strTrim(){
        return arguments[0].replace(/^\s+|\s+$/g,"");
    }

    function _quickviewJnit(){
        var selectorObj = arguments[0];
        var listprod = $$(selectorObj.itemClass);
        var mypath = 'quickview/index/view';
        var baseUrl = Trego.Quickview.BASE_URL + mypath;

        var _quickviewHref = "<a id=\"trego_quickview_handler\" href=\"#\" style=\"position:absolute;top:0;left:-999em; background-color: #535451; color: #fff; padding: 5px;\">"+Trego.Quickview.QV_TITLE+"</a>";
        $(document.body).append(_quickviewHref);
        var quickviewHandlerImg = $('#trego_quickview_handler img');
        $.each(listprod, function(index, value) {
            var reloadurl = baseUrl;
            //get reload url
            myhref = $(value).find(selectorObj.aClass);
            if (myhref.length == 0) return;
            var prodHref = readHref(myhref.attr('href'))[0];
            prodHref[0] == "\/" ? prodHref = prodHref.substring(1,prodHref.length) : prodHref;
            prodHref=strTrim(prodHref);

            reloadurl = baseUrl+"/path/"+prodHref;
            version = ieVersion();
            if(version < 8.0 && version > -1){
                reloadurl = baseUrl+"/path"+prodHref;
            }
            //end reload url
            
            $(this).find(".product-image-area").mouseover(function() {
                if ($(window).width() <= 768 ) return;
                if (this.className == 'i_new') return;
                $('#trego_quickview_handler').appendTo($(this));
                $('#trego_quickview_handler img').show();
                $('#trego_quickview_handler').css('top','50%');
                $('#trego_quickview_handler').css('left','50%');
                var margin_left = "-44px";
                var margin_top = "-14px";
                if($('#trego_quickview_handler').find("img").height()>0)
                    margin_top = '-'+$('#trego_quickview_handler').height()/2+'px';
                if($('#trego_quickview_handler').find("img").width()>0)
                    margin_left = '-'+$('#trego_quickview_handler').width()/2+'px';
                $('#trego_quickview_handler').css('margin-top',margin_top);
                $('#trego_quickview_handler').css('margin-left',margin_left);
                $('#trego_quickview_handler').attr('href',reloadurl).fadeIn();
                return false;
            }).mouseleave(function() {
                $('#trego_quickview_handler').hide();
                return false;
            });
        });

        //fix bug image disapper when hover
        $('#trego_quickview_handler')
            .bind('mouseover', function() {
                $(this).show();
                return false;
            })
            .bind('click', function() {
                $(this).hide();
            });
        //insert quickview popup
        $('#trego_quickview_handler').fancybox({
            'type'              : 'ajax',
            'scrolling'         : 'auto',
            'padding'           : 0,
            'margin'            : 0,
            'autoSize'          : false,
            'width'             : Trego.Quickview.QV_FRM_WIDTH,
            'height'            : 'auto',
            'afterLoad'        : function() {
                $('#fancybox-content').height('auto');
            }
        });
    }

    //end base function

    if (typeof jqSmartCatalog != 'undefined') {
        jqSmartCatalog(document).bind('smart-pagination-ajax-after', function() {
            _quickviewJnit(opt);
        });
    }

    _quickviewJnit(opt);
});
<?php endif; ?>
                    }
                })
            } catch (e) {}
        });
        active = false
    }
    return false
}
<?php endif; ?> 

function callback(){
	<?php echo $this->getCallbackJs(); ?>	
}
</script>

