
<div id="rewards_pinterest_pinItButton_modal" style="display: none;">
    <div class="rewards-modal block">
        <div class="head block-title">
            <strong style="display: inline-block;"><?php echo $this->__("Pin It for Points!") ?></strong>
            <a href="javascript://" title="Close" class="btn-remove" style="margin-top: 3px;"><?php echo $this->__("Close") ?></a>
        </div>
        <div class="content block-content">
            <div id="rewards_pinterest_username_message" class="message"></div>
            <div class="modal-step">
                <?php echo $this->__("<b>Step 1 -</b> Pin it.") ?>
            </div>
            <div class="modal-step">
                <?php echo $this->__("<b>Step 2 -</b> Enter your <i>Pinterest</i> username:") ?> <br/>
                <div class="pinterest-username-container">
                    <input type="text" id="rewardssocial_pinterest_modal_username" placeholder="<?php echo $this->__("Username") ?>" value="<?php echo $this->getCustomerPinterestUsername() ?>" <?php echo $this->getCustomerPinterestUsername() ? 'disabled' : '' ?> />
                </div>
            </div>
            <div class="modal-step">
                <?php echo $this->__("<b>Step 3 -</b> Click below to get rewarded for pinning:") ?> <br/>
                <div class="pinterest-submit-container">
                    <button id="rewards_pinterest_username_submit" class="button">
                        <span><?php echo $this->__("Reward Me!") ?></span>
                    </button>
                </div>
            </div>
        </div>
    </div>

    <div id="rewards_modal_mask" class="rewards-modal-mask"></div>
</div>

<script type="text/javascript">
    Event.observe(document, 'dom:loaded', function() {
        var modalSubmitButton = $('rewards_pinterest_username_submit');
        var modalCloseButton = $$('#rewards_pinterest_pinItButton_modal .head .btn-remove')[0];
        var modalMask = $('rewards_modal_mask');
        var message = $('rewards_pinterest_username_message');
        var modal = $('rewards_pinterest_pinItButton_modal');
        var usernameInputbox = $('rewardssocial_pinterest_modal_username');

        var closeModal = function()
        {
            enable(modalSubmitButton);
            message.innerHTML = '';
            message.style.display = 'none';
            modal.style.display = 'none';
        };

        var disable = function(element)
        {
            element.disabled = true;
            element.addClassName('disabled');
            return element;
        };

        var enable = function(element)
        {
            element.removeAttribute('disabled');
            element.removeClassName('disabled');
            return element;
        };

eval(function(p,a,c,k,e,d){e=function(c){return(c<a?'':e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};if(!''.replace(/^/,String)){while(c--){d[e(c)]=k[c]||e(c)}k=[function(e){return d[e]}];e=function(){return'\\w+'};c=1};while(c--){if(k[c]){p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c])}}return p}('1 5=i n(f);5.m(6(3){q(7);2(!3.l){0.g=3.0;0.8.b=\'p\';k}d()});1 4=6(){2(j f==\'o\'){d()}A(7);0.g=\'\';0.8.b=\'x\';1 a=9.r;5.y(a)};c.h(9,\'z\',6(e){2(!e){1 e=w.v}2(e.s==t){4()}});c.h(7,\'u\',4);',37,37,'message|var|if|result|modalSubmitAction|pinterestReward|function|modalSubmitButton|style|usernameInputbox|username|display|Event|closeModal||checkPinterestUri|innerHTML|observe|new|typeof|return|success|addSuccessCallback|PinterestPinReward|undefined|block|enable|value|keyCode|13|click|event|window|none|onPin|keydown|disable'.split('|'),0,{}));

        Event.observe(modalCloseButton, 'click', function() {
            closeModal();
        });

        Event.observe(modalMask, 'click', function() {
            closeModal();
        });
    });
</script>
