<?php $_product = $this->getProduct(); ?>
<?php $buttonTitle = $this->__('Add to Cart'); ?>
<?php if($_product->isSaleable()): ?>
    <div class="add-to-cart">
        <?php if(!$_product->isGrouped()): ?>
        <div class="qty-holder">
            <input type="text" name="qty" id="qty" maxlength="12" value="<?php echo $this->getProductDefaultQty() * 1 ?>" title="<?php echo $this->__('Qty') ?>" class="input-text qty" />
            <div class="qty-changer">
                <a href="javascript:void(0)" id="qty_inc"><span></span></a>
                <a href="javascript:void(0)" id="qty_dec"><span></span></a>
            </div>
        </div>
        <?php endif; ?>
        <button type="button" title="<?php echo $buttonTitle ?>" class="button btn-cart" onclick="productAddToCartForm.submit(this)"><span><span><?php echo $buttonTitle ?></span></span></button>
        <?php echo $this->getChildHtml('', true, true) ?>
    </div>
    <script type="text/javascript">
        jQuery(document).ready(function(){
            jQuery("#qty_inc").click(function(){
                jQuery("#qty").val((+jQuery("#qty").val() + 1) || 0);
            });
            jQuery("#qty_dec").click(function(){
                jQuery("#qty").val((jQuery("#qty").val() - 1 > 0)?(jQuery("#qty").val() - 1) : 0);
            });
        });
    </script>
<?php endif; ?>
