<?php
    $_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');
    $store = Mage::app()->getStore();
    $code  = $store->getCode();
?>
<?php
    $ratio_width = Mage::getStoreConfig("trego_settings/product_view/ratio_width", $code);
    $ratio_height = Mage::getStoreConfig("trego_settings/product_view/ratio_height", $code);
    $ratio = $ratio_height / $ratio_width;
    $rnd_str = rtrim(base64_encode(md5(microtime())),"=");
?>
<?php if (count($this->getGalleryImages()) > 0): ?>
<ul id="etalage">
<?php foreach ($this->getGalleryImages() as $_image): ?>
    <li>
        <?php
            $image_src = $this->helper('catalog/image')->init($_product, 'thumbnail', $_image->getFile())->resize(700, 700*$ratio);
        ?>
        <a rel="gallery" class="fancy-images fancy-images_<?php echo $rnd_str; ?>" href="<?php echo $image_src; ?>"><span class="glyphicon glyphicon-search"></span></a>
        <img width="344" height="344" class="etalage_thumb_image" id="image" src="<?php echo $image_src; ?>">
        <img width="100" height="100" class="etalage_source_image" src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail', $_image->getFile())->resize(100, 100*$ratio)?>" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>">
    </li>
<?php endforeach; ?>
</ul>
<?php else: ?>
<ul id="etalage">
    <li>
        <?php
            $image_src = $this->helper('catalog/image')->init($_product, 'image')->resize(700, 1000*$ratio);
        ?>
        <a class="fancy-images fancy-images_<?php echo $rnd_str; ?>" href="<?php echo $image_src; ?>"><span class="glyphicon glyphicon-search"></span></a>
        <img width="344" height="344" class="etalage_thumb_image" src="<?php echo $image_src; ?>">
        <img width="100" height="100" class="etalage_source_image" src="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize(100, 100*$ratio)?>" alt="<?php echo $this->htmlEscape($this->getImageLabel()) ?>">
    </li>
</ul>
<?php endif; ?>
<div class="etalage-control">
    <a href="javascript:void(0)" class="etalage-prev">Previous</a>
    <a href="javascript:void(0)" class="etalage-next">Next</a>
</div>
<script type="text/javascript">
    jQuery(document).ready(function(){
        reloadEtalage();
        jQuery(".product-img-box .etalage li.etalage_thumb");
        setTimeout(function(){reloadEtalage();}, 500);
        jQuery(window).resize(function(e){
            reloadEtalage();
        });
        jQuery('.etalage-prev').on('click', function(){
            etalage_previous();
        });

        jQuery('.etalage-next').on('click', function(){
            etalage_next();
        });
        jQuery("a.fancy-images_<?php echo $rnd_str; ?>").fancybox();
        function reloadEtalage(){
            var width = jQuery('.product-view .product-img-box').width();
            var src_img_width = 1000;
            var src_img_height = 1000;
            var ratio_width = <?php echo $ratio_width; ?>;
            var ratio_height = <?php echo $ratio_height; ?>;
            
            src_img_width = 700 * ratio_width / ratio_height;
            src_img_height = 700;
            var height = width * ratio_height / ratio_width;
            zoom_enabled = false;
            jQuery('#etalage').etalage({
                thumb_image_width: width,
                thumb_image_height: height,
                source_image_width: src_img_width,
                source_image_height: src_img_height,
                zoom_area_width: width,
                zoom_area_height: height,
                zoom_enable: zoom_enabled,
                smallthumb_hide_single: true,
                smallthumbs_position: 'bottom',
                show_icon: false,
                autoplay: false
            });
            jQuery('.product-view .product-img-box .etalage-control a').css('bottom',((jQuery('.etalage_small_thumbs').height()-25)/2)+"px");
        }
    });
</script>
<div class="clear"></div>