<div id="shoppingcart-promotion" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="promo_rule" id="catalog_rule"><?php echo $this->getChildChildHtml('shoppingcartrule_catalogrule','promotionalgift.shoppingcartcategory')?$this->getChildChildHtml('shoppingcartrule_catalogrule','promotionalgift.shoppingcartcategory'):$this->getChildChildHtml('shoppingcartrule_catalogrule','promotionalgift.shoppingcartcategory.checkout'); ?></div>
        </div>
    </div>
</div>
<div id="catalog-promotion" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="promo_rule" id="shoppingcart_rule"><?php echo $this->getChildChildHtml('shoppingcartrule_catalogrule','promotionalgift.shoppingcart')?$this->getChildChildHtml('shoppingcartrule_catalogrule','promotionalgift.shoppingcart'):$this->getChildChildHtml('shoppingcartrule_catalogrule','promotional-banner'); ?></div>
        </div>
    </div>
</div>
