<?php
/* @var Mage_Wishlist_Model_Item $item */
$item = $this->getItem();
$product = $item->getProduct();
?>
<h3 class="product-name"><a href="<?php echo $this->getProductUrl($item) ?>" title="<?php echo $this->escapeHtml($product->getName()) ?>"><?php echo $this->escapeHtml($product->getName()) ?></a></h3>
<div class="description std"><div class="inner"><?php echo $this->escapeHtml($this->stripTags($product->getShortDescription()));?></div></div>
<textarea name="description[<?php echo $item->getWishlistItemId() ?>]" rows="3" cols="5" placeholder="<?php echo $this->__('Please, enter your comments...') ?>" title="<?php echo $this->__('Comment') ?>"><?php echo ($this->escapeHtml($item->getDescription())) ?></textarea>
<?php if($this->getSortedChildren()): ?>
    <div class="item-manage">
    <?php foreach($this->getSortedChildren() as $childName):?>
        <?php echo $this->getChildHtml($childName, false);?>
    <?php endforeach;?>
    </div>
<?php endif; ?>
