<?php if ($this->getMethod()->getRib() || $this->getMethod()->getInformation()): ?>
        <ul class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
            <li>
                <div class="input-box">
                    <?php if ($this->getMethod()->getInformation()): ?>
                        <label style="color:#c00"><?php echo $this->getMethod()->getInformation(); ?></label>
                    <?php endif; ?>
                    <?php if ($this->getMethod()->getRib()): ?>
                        <div class="rib">
                            <?php echo nl2br($this->getMethod()->getRib()) ?>
                        </div>
                    <?php endif; ?>
                </div>
            </li>
        </ul>
<?php endif; ?>