<?php
$store = Mage::app()->getStore();
$code  = $store->getCode();
    $_enabled = Mage::getStoreConfig('socialicons/general/enabled', $code);
    $_facebook_visible = Mage::getStoreConfig('socialicons/options/facebook_visible', $code);
    $_facebook_url = Mage::getStoreConfig('socialicons/options/facebook_url', $code);
    $_facebook_sortorder = Mage::getStoreConfig('socialicons/options/facebook_sortorder', $code);
    $_twitter_visible = Mage::getStoreConfig('socialicons/options/twitter_visible', $code);
    $_twitter_url = Mage::getStoreConfig('socialicons/options/twitter_url', $code);
    $_twitter_sortorder = Mage::getStoreConfig('socialicons/options/twitter_sortorder', $code);
    $_linkedin_visible = Mage::getStoreConfig('socialicons/options/linkedin_visible', $code);
    $_linkedin_url = Mage::getStoreConfig('socialicons/options/linkedin_url', $code);
    $_linkedin_sortorder = Mage::getStoreConfig('socialicons/options/linkedin_sortorder', $code);
    $_instagram_visible = Mage::getStoreConfig('socialicons/options/instagram_visible', $code);
    $_instagram_url = Mage::getStoreConfig('socialicons/options/instagram_url', $code);
    $_instagram_sortorder = Mage::getStoreConfig('socialicons/options/instagram_sortorder', $code);
    $_googleplus_visible = Mage::getStoreConfig('socialicons/options/googleplus_visible', $code);
    $_googleplus_url = Mage::getStoreConfig('socialicons/options/googleplus_url', $code);
    $_googleplus_sortorder = Mage::getStoreConfig('socialicons/options/googleplus_sortorder', $code);
    $_links = array(
        array('visible'=>$_facebook_visible,'url'=>$_facebook_url,'class'=>'facebook-icon','title'=>'Facebook','sortorder'=>$_facebook_sortorder),
        array('visible'=>$_twitter_visible,'url'=>$_twitter_url,'class'=>'twitter-icon','title'=>'Twitter','sortorder'=>$_twitter_sortorder),
        array('visible'=>$_linkedin_visible,'url'=>$_linkedin_url,'class'=>'linkedin-icon','title'=>'Linkedin','sortorder'=>$_linkedin_sortorder),
        array('visible'=>$_instagram_visible,'url'=>$_instagram_url,'class'=>'instagram-icon','title'=>'Instagram','sortorder'=>$_instagram_sortorder),
        array('visible'=>$_googleplus_visible,'url'=>$_googleplus_url,'class'=>'googleplus-icon','title'=>'Googleplus','sortorder'=>$_googleplus_sortorder)
    );
    if (!function_exists('sortorder')) {
    function sortorder($item1,$item2)
    {
        if ($item1['sortorder'] == $item2['sortorder']) return 0;
        return ($item1['sortorder'] < $item2['sortorder']) ? -1 : 1;
    }
    }
    usort($_links,'sortorder');
    if($_enabled){
?>
<div class="social-icons">
<?php
   foreach($_links as $_link){
       if($_link['visible']==1){
           echo '<a href="'.$_link['url'].'" title="'.$_link['title'].'" class="'.$_link['class'].'" target="_blank">'.$_link['title'].'</a>';
       }
	}}
?>
</div>