<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="page-title">
    <h1><?php echo $this->__('My Product Reviews') ?></h1>
</div>
<?php if( $this->getCollection() && $this->count()): ?>
        <table class="data-table" id="my-reviews-table">
            <col width="1" />
            <col width="210" />
            <col width="1" />
            <col />
            <col width="1" />
            <thead>
                <tr class="for-desktop">
                    <th><?php echo $this->__('Date') ?></th>
                    <th><?php echo $this->__('Product') ?></th>
                    <th><?php echo $this->__('Rating') ?></th>
                    <th><?php echo $this->__('Review') ?></th>
                    <th class="last">&nbsp;</th>
                </tr>
                <tr class="for-mobile">
                    <th colspan="5" class="last"><?php echo $this->__('My Reviews')?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->getCollection() as $_review): ?>
                <tr class="for-desktop">
                    <td><span class="nobr"><?php echo $this->dateFormat($_review->getReviewCreatedAt()); ?></span></td>
                    <td><h2 class="product-name"><a href="<?php echo $this->getProductLink() ?>id/<?php echo $_review->getEntityPkValue() ?>"><?php echo $this->htmlEscape($_review->getName()) ?></a></h2></td>
                    <td>
                    <?php if($_review->getSum()): ?>
                        <div class="rating-box">
                            <div class="rating" style="width:<?php echo ( $_review->getSum() / $_review->getCount() ) ?>%;"></div>
                        </div>
                    <?php endif; ?>
                    </td>
                    <td><?php echo $this->helper('review')->getDetailHtml($_review->getDetail()) ?></td>
                    <td><a href="<?php echo $this->getReviewLink() ?>id/<?php echo $_review->getReviewId() ?>" class="nobr"><?php echo $this->__('View Details') ?></a></td>
                </tr>
                <tr class="for-mobile">
                    <td colspan="5" class="last">
                        <div><span class="nobr"><?php echo $this->dateFormat($_review->getReviewCreatedAt()); ?></span></div>
                        <div><h2 class="product-name"><a href="<?php echo $this->getProductLink() ?>id/<?php echo $_review->getEntityPkValue() ?>"><?php echo $this->htmlEscape($_review->getName()) ?></a></h2></div>
                        <div>
                        <?php if($_review->getSum()): ?>
                            <div class="rating-box">
                                <div class="rating" style="width:<?php echo ( $_review->getSum() / $_review->getCount() ) ?>%;"></div>
                            </div>
                        <?php endif; ?>
                        </div>
                        <div><?php echo $this->helper('review')->getDetailHtml($_review->getDetail()) ?></div>
                        <div><a href="<?php echo $this->getReviewLink() ?>id/<?php echo $_review->getReviewId() ?>" class="nobr"><?php echo $this->__('View Details') ?></a></div>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        <script type="text/javascript">decorateTable('my-reviews-table')</script>
    <?php echo $this->getToolbarHtml() ?>
<?php else: ?>
    <p><?php echo $this->__('You have submitted no reviews.') ?></p>
<?php endif; ?>
<div class="buttons-set">
    <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
</div>
